/** Server-side mirror of client safe defaults (schema v1). */
export const SERVER_DEFAULT_FLAGS = {
  globalKill: {
    key: 'globalKill',
    kind: 'kill',
    enabled: false,
    percentage: 100,
  },
  aiChatEnabled: { key: 'aiChatEnabled', kind: 'boolean', enabled: true, percentage: 100 },
  personalIntelligenceEnabled: {
    key: 'personalIntelligenceEnabled',
    kind: 'boolean',
    enabled: true,
    percentage: 100,
  },
  mentorEnabled: { key: 'mentorEnabled', kind: 'boolean', enabled: true, percentage: 100 },
  academyEnabled: { key: 'academyEnabled', kind: 'boolean', enabled: true, percentage: 100 },
  decisionReinforcementEnabled: {
    key: 'decisionReinforcementEnabled',
    kind: 'boolean',
    enabled: true,
    percentage: 100,
  },
  aggressiveMarketPollingEnabled: {
    key: 'aggressiveMarketPollingEnabled',
    kind: 'boolean',
    enabled: false,
    percentage: 100,
  },
};

export const SERVER_DEFAULT_REMOTE = {
  schemaVersion: 1,
  aiModel: 'tradevision-engine-2.0',
  aiDailyLimitFree: 3,
  aiDailyLimitPremium: 100,
  aiMentorMonthlyFree: 3,
  aiAnalysisMonthlyFree: 3,
  aiAnalysisMonthlyPremium: 100,
  replaySessionsMonthlyFree: 5,
  watchlistCountFree: 1,
  symbolsPerWatchlistFree: 15,
  portfolioPositionsFree: 10,
  alertsMaxFree: 5,
  researchQueueDepthFree: 3,
  marketQuotePollMs: 45_000,
  marketCandlePollMs: 120_000,
  alertEvalIntervalMs: 45_000,
  academyContentEnabled: true,
  mentorWeeklyChallengeEnabled: true,
  decisionBriefMaxSetups: 5,
  decisionBriefMinRvs: 40,
  notificationQuietHoursStart: 22,
  notificationQuietHoursEnd: 7,
  marketRefreshAggressiveness: 'balanced',
  storePromoMessage:
    'Continue your growth with deeper DNA, Decision Graph, and fair-use AI coaching — educational process tools only.',
  storePromoEnabled: false,
  analyticsSampleRate: 1,
  perfSampleRate: 0.2,
  sentryTracesSampleRate: 0.05,
  spikeAlertSecurityEventsPerHour: 200,
  backupRetentionDays: 30,
};
