import type { LearningConceptNode } from '../types/learning-engine.types';

/**
 * Concept graph used by Today’s Training and spaced review.
 * Canonical competency IDs and mastery states live in
 * `features/competency` — this graph remains a navigation/recommendation layer.
 * IDs match Academy conceptIds / mastery maps where those exist.
 */
export const LEARNING_CONCEPTS: LearningConceptNode[] = [
  {
    id: 'rsi',
    title: 'RSI',
    relatedIds: ['momentum', 'divergence', 'false-signals'],
    examplePath: ['rsi', 'momentum', 'chart-interpretation', 'divergence', 'false-signals'],
    skillDomain: 'technical_analysis',
    lessonIds: ['ta-rsi'],
    drillIds: ['missing-evidence'],
    replayIds: ['false-breakout-drill'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'momentum',
    title: 'Momentum',
    relatedIds: ['rsi', 'chart-interpretation', 'divergence'],
    skillDomain: 'technical_analysis',
    lessonIds: ['ta-momentum', 'ta-trend-range'],
    drillIds: ['identify-trend'],
    replayIds: ['tesla-rally'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'chart-interpretation',
    title: 'Chart interpretation',
    relatedIds: ['momentum', 'support', 'false-breakouts'],
    skillDomain: 'chart_reading',
    lessonIds: ['ta-candles', 'ta-trend-range'],
    drillIds: ['identify-trend'],
    replayIds: ['false-breakout-drill'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'divergence',
    title: 'Divergence',
    relatedIds: ['rsi', 'momentum', 'false-signals'],
    skillDomain: 'technical_analysis',
    lessonIds: ['ta-divergence'],
    drillIds: ['missing-evidence'],
    replayIds: ['false-breakout-drill'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'false-signals',
    title: 'False signals',
    relatedIds: ['divergence', 'false-breakouts', 'rsi'],
    skillDomain: 'technical_analysis',
    lessonIds: ['ta-false-breakouts'],
    drillIds: ['breakout-quality'],
    replayIds: ['false-breakout-drill'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'support',
    title: 'Support and resistance',
    relatedIds: ['chart-interpretation', 'false-breakouts', 'invalidation'],
    skillDomain: 'chart_reading',
    lessonIds: ['ta-structure'],
    drillIds: ['find-support', 'breakout-quality'],
    replayIds: ['false-breakout-drill'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'false-breakouts',
    title: 'False breakouts',
    relatedIds: ['support', 'false-signals', 'invalidation'],
    skillDomain: 'technical_analysis',
    lessonIds: ['ta-false-breakouts'],
    drillIds: ['breakout-quality'],
    replayIds: ['false-breakout-drill'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'position-sizing',
    title: 'Position sizing',
    relatedIds: ['risk-per-trade', 'invalidation'],
    skillDomain: 'risk_management',
    lessonIds: ['risk-position-sizing', 'risk-per-trade'],
    drillIds: ['position-size', 'rr-compare'],
    replayIds: ['gold-regime-risk'],
    simulateHref: '/simulate?start=1',
    journalMistakes: ['size'],
  },
  {
    id: 'risk-per-trade',
    title: 'Risk per trade',
    relatedIds: ['position-sizing', 'invalidation'],
    skillDomain: 'risk_management',
    lessonIds: ['risk-per-trade', 'basics-rr'],
    drillIds: ['rr-compare', 'position-size'],
    replayIds: ['gold-regime-risk'],
    simulateHref: '/simulate?start=1',
    journalMistakes: ['size'],
  },
  {
    id: 'invalidation',
    title: 'Invalidation',
    relatedIds: ['position-sizing', 'thesis', 'support'],
    skillDomain: 'decision_making',
    lessonIds: ['dec-invalidation', 'risk-stops'],
    drillIds: ['name-invalidation', 'rr-compare'],
    replayIds: ['failed-setup-patience'],
    simulateHref: '/simulate?start=1',
    journalMistakes: ['invalidation'],
  },
  {
    id: 'thesis',
    title: 'Thesis and evidence',
    relatedIds: ['invalidation', 'uncertainty', 'confirmation-bias'],
    skillDomain: 'decision_making',
    lessonIds: ['dec-thesis'],
    drillIds: ['missing-evidence'],
    replayIds: ['nvidia-earnings', 'failed-setup-patience'],
    simulateHref: '/simulate?start=1',
    journalMistakes: ['no_plan'],
  },
  {
    id: 'uncertainty',
    title: 'Uncertainty',
    relatedIds: ['thesis', 'event-risk'],
    skillDomain: 'decision_making',
    lessonIds: ['dec-uncertainty'],
    drillIds: ['rate-decision-uncertainty'],
    replayIds: ['fomc-decision-lab'],
    simulateHref: '/simulate?start=1&prep=macro',
  },
  {
    id: 'confirmation-bias',
    title: 'Confirmation bias',
    relatedIds: ['thesis', 'overconfidence'],
    skillDomain: 'psychology',
    lessonIds: ['psych-confirmation', 'dec-psychology'],
    drillIds: ['confirmation-bias'],
    replayIds: ['failed-setup-patience'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'overconfidence',
    title: 'Confidence calibration',
    relatedIds: ['confirmation-bias', 'position-sizing'],
    skillDomain: 'psychology',
    lessonIds: ['psych-overconfidence'],
    drillIds: ['confidence-check'],
    replayIds: ['failed-setup-patience'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'fomo',
    title: 'Emotional decisions',
    relatedIds: ['overconfidence', 'position-sizing'],
    skillDomain: 'psychology',
    lessonIds: ['psych-fomo', 'psych-revenge'],
    drillIds: ['fomo-chase'],
    replayIds: ['gamestop-squeeze'],
    simulateHref: '/simulate?start=1',
    journalMistakes: ['fomo', 'revenge'],
  },
  {
    id: 'volatility-aware-risk',
    title: 'Volatility-aware risk',
    relatedIds: ['position-sizing', 'risk-per-trade', 'event-risk'],
    skillDomain: 'risk_management',
    lessonIds: ['foundations-volatility'],
    drillIds: ['volatility-size'],
    replayIds: ['black-monday'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'revenge-trading',
    title: 'Revenge trading',
    relatedIds: ['fomo', 'overconfidence', 'discipline'],
    skillDomain: 'psychology',
    lessonIds: ['psych-revenge'],
    drillIds: ['revenge-interrupt'],
    replayIds: ['failed-setup-patience'],
    simulateHref: '/simulate?start=1',
    journalMistakes: ['revenge'],
  },
  {
    id: 'diversification',
    title: 'Diversification',
    relatedIds: ['position-sizing', 'event-risk'],
    skillDomain: 'portfolio_management',
    lessonIds: ['port-diversification', 'risk-exposure'],
    drillIds: ['rr-compare'],
    replayIds: ['sector-rotation-lab'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'event-risk',
    title: 'Event risk',
    relatedIds: ['uncertainty', 'earnings', 'interest-rates'],
    skillDomain: 'fundamental_analysis',
    lessonIds: ['fund-calendar', 'fund-economy'],
    drillIds: ['rate-decision-uncertainty', 'inflation-asset-effects'],
    replayIds: ['inflation-shock-2022', 'brexit-night'],
    simulateHref: '/simulate?start=1&prep=macro',
    eventKinds: ['interest_rate', 'inflation', 'employment', 'gdp'],
  },
  {
    id: 'interest-rates',
    title: 'Interest rates',
    relatedIds: ['event-risk', 'uncertainty'],
    skillDomain: 'fundamental_analysis',
    lessonIds: ['fund-economy'],
    drillIds: ['rate-decision-uncertainty'],
    replayIds: ['fomc-decision-lab'],
    simulateHref: '/simulate?start=1&prep=rates',
    eventKinds: ['interest_rate'],
  },
  {
    id: 'earnings',
    title: 'Earnings',
    relatedIds: ['event-risk', 'thesis', 'revenue-growth', 'valuation'],
    skillDomain: 'fundamental_analysis',
    lessonIds: ['fund-statements', 'fund-basics'],
    drillIds: ['changing-margins', 'growth-vs-quality'],
    replayIds: ['nvidia-earnings', 'guidance-cut-lab'],
    simulateHref: '/simulate?start=1&prep=earnings',
    eventKinds: ['earnings', 'corporate'],
  },
  {
    id: 'revenue-growth',
    title: 'Revenue growth',
    relatedIds: ['earnings', 'business-quality'],
    skillDomain: 'fundamental_analysis',
    lessonIds: ['fund-statements'],
    drillIds: ['compare-two-businesses', 'growth-vs-quality'],
    replayIds: ['nvidia-earnings'],
    simulateHref: '/simulate?start=1&prep=earnings',
  },
  {
    id: 'valuation',
    title: 'Valuation',
    relatedIds: ['earnings', 'business-quality', 'fundamental-uncertainty'],
    skillDomain: 'fundamental_analysis',
    lessonIds: ['fund-valuation-quality'],
    drillIds: ['valuation-uncertainty', 'growth-vs-quality'],
    replayIds: ['guidance-cut-lab'],
    simulateHref: '/simulate?start=1&prep=earnings',
  },
  {
    id: 'balance-sheet',
    title: 'Balance sheet',
    relatedIds: ['business-quality', 'earnings'],
    skillDomain: 'fundamental_analysis',
    lessonIds: ['fund-statements'],
    drillIds: ['balance-sheet-risk'],
    replayIds: ['guidance-cut-lab'],
    simulateHref: '/simulate?start=1',
  },
  {
    id: 'competitive-position',
    title: 'Competitive position',
    relatedIds: ['business-quality', 'revenue-growth'],
    skillDomain: 'fundamental_analysis',
    lessonIds: ['fund-valuation-quality'],
    drillIds: ['compare-two-businesses', 'valuation-uncertainty'],
    replayIds: ['guidance-cut-lab'],
    simulateHref: '/simulate?start=1&prep=earnings',
  },
  {
    id: 'business-quality',
    title: 'Business quality',
    relatedIds: ['competitive-position', 'revenue-growth', 'balance-sheet'],
    skillDomain: 'fundamental_analysis',
    lessonIds: ['fund-basics', 'fund-valuation-quality'],
    drillIds: ['compare-two-businesses', 'growth-vs-quality'],
    replayIds: ['nvidia-earnings'],
    simulateHref: '/simulate?start=1&prep=earnings',
  },
  {
    id: 'fundamental-uncertainty',
    title: 'Fundamental uncertainty',
    relatedIds: ['uncertainty', 'valuation', 'earnings'],
    skillDomain: 'fundamental_analysis',
    lessonIds: ['fund-basics', 'fund-valuation-quality', 'fund-calendar'],
    drillIds: ['valuation-uncertainty', 'rate-decision-uncertainty'],
    replayIds: ['guidance-cut-lab', 'fomc-decision-lab'],
    simulateHref: '/simulate?start=1&prep=earnings',
    eventKinds: ['earnings', 'interest_rate'],
  },
  {
    id: 'fx',
    title: 'Currency pairs',
    relatedIds: ['event-risk'],
    skillDomain: 'market_understanding',
    lessonIds: ['foundations-fx'],
    drillIds: ['fx-convert'],
    replayIds: ['brexit-night'],
    simulateHref: '/simulate?start=1',
  },
];

export const SPACED_INTERVAL_DAYS = [1, 3, 7, 14] as const;

export {
  DRILL_TO_CONCEPT,
  LESSON_PRIMARY_CONCEPT,
} from '@/features/competency/content/activity-concept-map';
