import { makeFlagshipLesson, replayEpisodeLink } from './lesson-factory';
import type { Lesson } from '../types/academy.types';

const PRACTICE_CHART = {
  label: 'Open a practice drill',
  href: '/practice',
  description: 'Judge the chart. Write why, not just which box you tapped.',
};

const PRACTICE_RR = {
  label: 'Practice risk/reward',
  href: '/practice?drill=rr-compare',
  description: 'Compare two R:R sketches before you size anything.',
};

const SIMULATE = {
  label: 'Apply in paper trading',
  href: '/simulate',
  description: 'SIMULATED TRADING. Process first. Simulated P/L is not the grade.',
};

const REPLAY = {
  label: 'See it on Replay',
  href: '/decision/replay',
  description: 'Pause the tape. Name the structure before the next candle.',
};

const JOURNAL = {
  label: 'Journal the reasoning',
  href: '/journal?from=academy',
  description: 'Capture thesis, invalidation, and what you would change.',
};

function mcq(
  id: string,
  prompt: string,
  choices: string[],
  correctIndex: number,
  choiceExplanations: string[],
  conceptId: string,
): Lesson['quiz'][number] {
  return {
    id,
    prompt,
    choices,
    correctIndex,
    explanation: choiceExplanations[correctIndex] ?? '',
    choiceExplanations,
    conceptId,
  };
}

export const FLAGSHIP_LESSONS: Lesson[] = [
  makeFlagshipLesson({
    id: 'foundations-asset-classes',
    title: 'Asset classes: what you are actually practising',
    description: 'Stocks, ETFs, crypto, and FX behave differently. The skill is matching process to the instrument — not collecting tickers.',
    category: 'basics',
    difficulty: 'beginner',
    durationMinutes: 10,
    sortOrder: 2,
    tags: ['assets', 'stocks', 'etf', 'crypto', 'forex'],
    searchKeywords: ['asset class', 'what is an etf', 'crypto vs stock'],
    prerequisiteIds: ['foundations-market'],
    relatedLessonIds: ['foundations-fx', 'foundations-liquidity', 'basics-orders', 'crypto-structure'],
    conceptIds: ['asset-classes'],
    objectives: [
      'Name the main differences between equities, ETFs, crypto, and FX.',
      'Explain why hours, liquidity, and settlement change risk.',
      'Refuse to copy a stock playbook onto a 24-hour crypto tape without adjustment.',
    ],
    whyItMatters:
      'A “good setup” on an illiquid name is not the same decision as the same pattern on a large ETF. Process quality starts with knowing the vehicle.',
    explanation:
      'Equities are claims on businesses and usually trade in sessions. ETFs package a basket — useful for allocation, still not “the market itself”. Crypto trades nearly around the clock with different liquidity pockets. FX is a relative price between two currencies.\n\nNone of these are automatically better. They change gap risk, overnight exposure, and how honest a stop can be.',
    examples: [
      'A Swiss blue-chip and a thin small-cap can print the same candle shape. The small-cap stop is more likely to gap through.',
      'An ETF can look smooth while its constituents are chaotic. You own the basket, not a story stock.',
    ],
    mistakes: [
      'Treating crypto like a stock that simply never closes.',
      'Sizing FX as if pip distance equals equity stop distance without converting risk.',
    ],
    limitations: ['This lesson does not recommend any asset. It only names how the vehicle changes process.'],
    whenItFails: [
      'When you ignore hours and news calendars for the specific market.',
      'When correlation across “different” assets is actually one theme.',
    ],
    exercise: {
      id: 'ex-asset',
      kind: 'compare',
      prompt: 'Which comparison is the more honest process warning?',
      leftLabel: 'Same candle pattern ⇒ same trade on any asset',
      rightLabel: 'Same pattern, different hours/liquidity ⇒ different risk',
      correctIndex: 1,
      explanation: 'Pattern recognition without vehicle context is decoration. Risk lives in gaps, spreads, and sessions.',
      conceptId: 'asset-classes',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'Why can a stop that “worked” on a large ETF fail on a thin crypto pair?',
        [
          'Because crypto is always more profitable',
          'Because sessions, liquidity, and gap behaviour differ',
          'Because indicators stop working on crypto',
          'Because ETFs cannot fall',
        ],
        1,
        [
          'Profitability is not the lesson. Process is.',
          'Stops assume you can transact near a level. Thin, 24-hour tapes often violate that.',
          'Indicators can be plotted anywhere. They do not fix execution.',
          'ETFs can fall. The point is liquidity and structure, not immunity.',
        ],
        'asset-classes',
      ),
    ],
    takeaways: [
      'Name the vehicle before you copy a playbook.',
      'Hours and liquidity change whether a stop is honest.',
    ],
    practice: [PRACTICE_CHART],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'foundations-fx',
    title: 'Currency pairs: dollars, euros, and what a quote actually means',
    description:
      'FX is a relative price between two currencies. A USD account buying EUR/USD is not the same as exchanging holiday cash — and pip distance is not a stock-point distance.',
    category: 'basics',
    difficulty: 'beginner',
    durationMinutes: 12,
    sortOrder: 2.5,
    tags: ['forex', 'fx', 'currency', 'usd', 'eur', 'pip'],
    searchKeywords: [
      'currency pair',
      'how do i trade currencies',
      'what is eur usd',
      'base quote currency',
      'pip value',
      'currency conversion',
    ],
    prerequisiteIds: ['foundations-asset-classes', 'foundations-price'],
    relatedLessonIds: ['risk-position-sizing', 'foundations-liquidity', 'ta-structure'],
    conceptIds: ['fx', 'currency-pairs'],
    objectives: [
      'Name base vs quote on a pair such as EUR/USD.',
      'Convert a sample dollar amount into another currency without treating the rate as a live fill.',
      'Explain why a 0.01 move in USD/JPY is not the same cash risk as a $0.01 stock move.',
    ],
    whyItMatters:
      'US-first books still meet other currencies. If you ignore conversion, you size the pair as if it were a $185 stock. That is how paper (and live) accounts get quietly oversized.',
    explanation:
      'EUR/USD at 1.10 means one euro costs 1.10 US dollars. The first currency is the base; the second is the quote.\n\nA cash conversion (“I need €9,090 for a $10,000 trip at 1.10”) is not the same decision as a speculative EUR/USD position. The first is exchanging units. The second is taking a view on the relative price — still with a thesis, invalidation, and size in your account currency.\n\nTradeAcademy paper-trading converts sample pair prices into your account currency so the cash ledger stays honest. Rates are synthetic/sample, never a live venue.',
    chart: {
      id: 'fx-rr',
      kind: 'risk_reward',
      title: 'Invalidation still needs a distance you can convert',
      caption: 'Educational example. Entry, stop, and target are process marks — not a EUR/USD signal.',
    },
    examples: [
      '$10,000 at a sample EUR/USD of 1.10 buys about €9,091. That is conversion literacy, not a trade.',
      'USD/JPY quoted at 150: one dollar costs 150 yen. A 1-yen move is 1/150 of a dollar per dollar of notional — not “one point like AAPL”.',
    ],
    mistakes: [
      'Treating pip distance as stock-point distance.',
      'Sizing EUR/USD as if the quote were a share price in your account currency without converting.',
      'Calling a sample conversion a live FX fill.',
    ],
    limitations: [
      'These rates are labelled synthetic. Spreads, rolls, and session liquidity are not modelled as a broker would.',
    ],
    whenItFails: [
      'When the quote currency is not your account currency and you skip conversion.',
      'When you confuse exchanging cash with speculating on the pair.',
    ],
    exercise: {
      id: 'ex-fx-convert',
      kind: 'calculate',
      prompt: 'Sample EUR/USD is 1.10. How many euros does $11,000 buy at that rate? (Ignore spread.)',
      expectedValue: 10000,
      tolerance: 1,
      unit: 'EUR',
      explanation:
        'Amount in quote ÷ rate = amount in base when the pair is quoted as USD per 1 EUR. 11,000 / 1.10 = 10,000 euros. This is conversion, not a recommended trade.',
      conceptId: 'fx',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'EUR/USD is 1.08. What is the honest reading?',
        [
          'The euro will rise because 1.08 is oversold',
          'One euro currently costs 1.08 US dollars on this quote',
          'You should sell dollars',
          'Pip value equals one dollar for every account',
        ],
        1,
        [
          'A level is not a forecast. Oversold is not even defined here.',
          'Base/quote: EUR is the base, USD is the quote. The number is dollars per euro.',
          'No quote is a buy/sell instruction. Conversion literacy is not a signal.',
          'Pip value depends on pair, notional, and account currency.',
        ],
        'fx',
      ),
      mcq(
        'q2',
        'Your paper book is in USD. You buy USD/JPY. Why convert?',
        [
          'Because yen prices look larger, so the trade is safer',
          'Because the quote is in yen per dollar; cash risk in the USD book is the converted amount',
          'Because US traders are not allowed to look at JPY',
          'Because conversion guarantees profit',
        ],
        1,
        [
          'Larger numbers are not safer. Yen quotes are a different unit.',
          'The ledger must speak the account currency. Native quote × conversion = paper cash at risk.',
          'You can study any sample pair. The constraint is honest units, not nationality.',
          'Nothing about conversion guarantees P/L. Simulated P/L still does not grade the decision.',
        ],
        'fx',
      ),
    ],
    takeaways: [
      'Name base and quote before you size.',
      'Conversion literacy ≠ a directional view on the pair.',
      'Always express risk in the account currency — dollars unless you changed it.',
    ],
    practice: [
      {
        label: 'Practice a currency conversion',
        href: '/practice?drill=fx-convert',
        description: 'Convert a dollar amount at a sample rate. Reasoning first.',
      },
    ],
    simulation: [
      {
        label: 'Paper-trade a currency pair',
        href: '/simulate',
        description: 'SIMULATED. Converted into your account currency. Not a live FX venue.',
      },
    ],
  }),

  makeFlagshipLesson({
    id: 'foundations-price',
    title: 'Price is a transaction, not a verdict',
    description: 'A print is an agreed exchange at a moment. It is not proof that the next print will be higher or that you were “right”.',
    category: 'basics',
    difficulty: 'beginner',
    durationMinutes: 9,
    sortOrder: 3,
    tags: ['price', 'quotes', 'last'],
    searchKeywords: ['what is price', 'last price', 'quote'],
    prerequisiteIds: ['foundations-market'],
    relatedLessonIds: ['foundations-liquidity', 'ta-candles', 'basics-orders'],
    conceptIds: ['price'],
    objectives: [
      'Separate last price, bid/ask, and your fill.',
      'Treat a candle close as a summary, not a prophecy.',
    ],
    whyItMatters:
      'Chasing “the number on the screen” hides spread, delay, and sample data. TradeAcademy labels synthetic/sample quotes. Process still starts with what a price actually is.',
    explanation:
      'Last price is the most recent transaction. Bid and ask are offers. A candle compresses many transactions into open/high/low/close.\n\nNone of those numbers know your thesis. A green close is not permission to size up.',
    chart: {
      id: 'price-ohlc',
      kind: 'candles',
      title: 'A close is a summary',
      caption: 'Educational tape — not a live quote. The last close is not a forecast.',
    },
    examples: [
      'Two traders can both be “right” about direction and still have different fills because of spread.',
      'A synthetic educational chart can teach structure without being a broker quote.',
    ],
    mistakes: ['Treating last price as guaranteed next-fill price.', 'Ignoring that sample data is labelled sample.'],
    limitations: ['This app’s default market data is synthetic/sample. Never confuse it with a live venue.'],
    whenItFails: ['When you assume a labelled sample chart is a trading venue.', 'When you ignore slippage in thin names.'],
    exercise: {
      id: 'ex-price',
      kind: 'select',
      prompt: 'The close of an educational candle most honestly means…',
      choices: [
        'The next session must continue that direction',
        'A summary of transactions in that interval',
        'A buy or sell instruction',
        'Proof your thesis was correct',
      ],
      correctIndex: 1,
      choiceExplanations: [
        'Closes do not obligate the next interval.',
        'OHLC is compression of prints, not a verdict.',
        'Charts do not issue orders.',
        'Outcome and process are different questions.',
      ],
      explanation: 'Read candles as compressed history. Decisions still need invalidation and size.',
      conceptId: 'price',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'If last price ticks up, you should conclude…',
        [
          'The asset is a buy',
          'Someone transacted higher than the previous print — nothing more by itself',
          'Your simulated P/L is skill',
          'Bid/ask no longer matter',
        ],
        1,
        [
          'A print is not a recommendation.',
          'Price is a transaction record. Context and risk still do the work.',
          'Simulated P/L does not grade process.',
          'Spread still exists after a print.',
        ],
        'price',
      ),
    ],
    takeaways: ['Price is a print, not a grade.', 'Know whether you are looking at sample, delayed, or live data.'],
    practice: [PRACTICE_CHART],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'foundations-timeframes',
    title: 'Timeframes: the same market, different questions',
    description: 'A daily uptrend and a 15-minute mess can both be true. Timeframe is a question, not a personality.',
    category: 'basics',
    difficulty: 'beginner',
    durationMinutes: 11,
    sortOrder: 6,
    tags: ['timeframe', 'mtf', 'chart'],
    searchKeywords: ['multiple timeframes', 'which timeframe', 'daily vs 15 minute'],
    prerequisiteIds: ['ta-candles'],
    relatedLessonIds: ['ta-mtf', 'ta-trend-range', 'dec-regime'],
    conceptIds: ['timeframes'],
    objectives: [
      'State which question each timeframe is answering.',
      'Avoid mixing a scalp stop with a weekly thesis without saying so.',
    ],
    whyItMatters:
      'Most “the chart lied” stories are timeframe collisions. You sized for noise while arguing a higher-timeframe story.',
    explanation:
      'Higher timeframes describe context. Lower timeframes describe timing and noise. Alignment is useful; it is not a guarantee.\n\nIf you cannot name the timeframe of your invalidation, you do not have an invalidation.',
    chart: {
      id: 'tf-trend',
      kind: 'trend',
      title: 'Structure on one interval',
      caption: 'Educational daily-style tape. A lower interval of the same idea would look noisier.',
    },
    examples: [
      'Weekly trend up, daily pullback, 5-minute chop — three true statements.',
      'A stop under a 5-minute wick may have nothing to do with the daily thesis.',
    ],
    mistakes: ['Changing timeframe after entry to keep the story alive.', 'Using RSI(14) on 1-minute as if it were daily.'],
    limitations: ['No timeframe is “more correct”. Each answers a different question.'],
    whenItFails: ['News events that swamp all intervals.', 'Illiquid names where lower intervals are mostly noise.'],
    exercise: {
      id: 'ex-tf',
      kind: 'scenario',
      situation: 'You believe the daily trend is up. The 15-minute chart is messy.',
      prompt: 'What is the process-respecting next step?',
      choices: [
        'Short because the 15-minute looks weak',
        'Keep the daily thesis, and only time an entry if invalidation still matches that thesis',
        'Switch to weekly until it agrees with the 15-minute',
        'Increase size to “average in”',
      ],
      correctIndex: 1,
      explanation: 'Timeframe is a question. Size and stop must match the thesis timeframe.',
      conceptId: 'timeframes',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'A daily higher-high structure and a 15-minute downswing means…',
        [
          'The daily chart is wrong',
          'They can both be true — you must choose which question you are answering',
          'You should always trade the lowest timeframe',
          'Indicators will pick the winner',
        ],
        1,
        [
          'Higher timeframe context can coexist with lower timeframe noise.',
          'Name the question. Then size to that invalidation.',
          'Lower is not automatically better.',
          'Indicators do not resolve timeframe conflict for you.',
        ],
        'timeframes',
      ),
    ],
    takeaways: ['Invalidation has a timeframe.', 'Alignment helps; it does not remove uncertainty.'],
    practice: [REPLAY, PRACTICE_CHART],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'foundations-volatility',
    title: 'Volatility: how much it moves, not which way',
    description: 'Volatility is range. It tells you about stop distance and size, not about a guaranteed direction.',
    category: 'risk_management',
    difficulty: 'beginner',
    durationMinutes: 12,
    sortOrder: 8,
    tags: ['volatility', 'atr', 'range'],
    searchKeywords: ['what is volatility', 'atr', 'how much does it move'],
    prerequisiteIds: ['foundations-price', 'ta-candles'],
    relatedLessonIds: ['risk-position-sizing', 'dec-regime', 'risk-drawdown'],
    conceptIds: ['volatility-aware-risk'],
    objectives: [
      'Define volatility as movement, not as a buy/sell cue.',
      'Connect wider range to smaller size for the same cash risk.',
    ],
    whyItMatters:
      'People confuse “it is moving” with “I should trade more”. Usually the opposite is true for a fixed risk budget.',
    explanation:
      'If typical range doubles and your stop is structural, the same share count doubles cash risk. Position sizing is how you keep risk stable.\n\nHigh volatility can be opportunity or ruin. The difference is size and whether the regime matches your playbook.',
    chart: {
      id: 'vol-range',
      kind: 'candles',
      title: 'Range expansion is not a signal',
      caption: 'Educational wide-range bars. Expansion changes size math, not destiny.',
    },
    examples: [
      'Earnings week: range expands. Half-size is often the process move, not a prediction.',
      'A quiet ETF and a 10% crypto day are not the same 1% risk problem.',
    ],
    mistakes: ['Widening stops instead of reducing size.', 'Treating implied vol as a direction forecast.'],
    limitations: ['Historical range is not a promise of next-week range.'],
    whenItWorks: [
      'You already have a structure stop, then you cut quantity so cash risk stays at the budget when range expands.',
    ],
    whenItFails: ['Gaps through stops.', 'Regimes that shift faster than your lookback.'],
    exercise: {
      id: 'ex-vol',
      kind: 'calculate',
      prompt: 'Equity 100,000. Risk 1% = 1,000. Stop is 4.00 away (was 2.00 yesterday). What quantity keeps the same cash risk?',
      expectedValue: 250,
      tolerance: 0.01,
      unit: 'units',
      explanation: 'Quantity = cash risk / stop distance = 1000 / 4 = 250. Wider stop, fewer units.',
      conceptId: 'volatility-aware-risk',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'If volatility doubles and you keep the same quantity with a structure stop…',
        [
          'Risk stays the same',
          'Cash risk roughly doubles',
          'You are guaranteed a better R:R',
          'Drawdown cannot increase',
        ],
        1,
        [
          'Stop distance is part of risk.',
          'Same size, wider stop ⇒ more money at risk.',
          'R:R is a plan, not a gift from volatility.',
          'Larger risk usually means larger possible drawdown.',
        ],
        'volatility-aware-risk',
      ),
    ],
    takeaways: ['Volatility sizes the stop, then size follows.', 'Movement is not a permission slip.'],
    practice: [
      PRACTICE_RR,
      {
        label: 'Volatility size drill',
        href: '/practice?drill=volatility-size',
        description: 'Keep the cash-risk budget when range expands.',
      },
    ],
    simulation: [SIMULATE],
    replay: [replayEpisodeLink('black-monday', 'Gap-risk room — size for range, not for the story')],
  }),

  makeFlagshipLesson({
    id: 'foundations-liquidity',
    title: 'Liquidity: can you actually transact?',
    description: 'Liquidity is how much you can buy or sell without moving the price against yourself. Thin books create false breaks and dishonest stops.',
    category: 'basics',
    difficulty: 'beginner',
    durationMinutes: 10,
    sortOrder: 9,
    tags: ['liquidity', 'spread', 'slippage'],
    searchKeywords: ['thin market', 'spread', 'slippage', 'liquidity'],
    prerequisiteIds: ['basics-orders', 'foundations-price'],
    relatedLessonIds: ['foundations-asset-classes', 'ta-false-breakouts', 'risk-position-sizing'],
    conceptIds: ['liquidity'],
    objectives: [
      'Connect spread and depth to whether a stop is realistic.',
      'Treat a spike through a level on no volume as a question, not a confirmed break.',
    ],
    whyItMatters:
      'Beautiful charts on empty books are a trap. Process includes “can I get out near my invalidation?”',
    explanation:
      'Tight spreads and deep books absorb size. Wide spreads and empty books mean your fill is part of the move.\n\nFalse breakouts cluster where liquidity is poor: a few prints can tag a stop and reverse.',
    chart: {
      id: 'liq-break',
      kind: 'breakout',
      title: 'A poke is not acceptance',
      caption: 'Educational range with a failed hold. Thin prints can look like breaks.',
    },
    examples: [
      'A one-tick break on tiny volume that immediately returns inside the range.',
      'Simulated market orders assume a fill. Live thin names may not.',
    ],
    mistakes: ['Placing stops in obvious liquidity pools without accepting they may be hunted — and still calling it “manipulation” as a plan.', 'Ignoring spread in R:R math.'],
    limitations: ['This lesson cannot show a live order book. It teaches the idea.'],
    whenItFails: ['When you assume paper fills equal live fills.', 'During halts and gaps.'],
    exercise: {
      id: 'ex-liq',
      kind: 'identify',
      prompt: 'On the educational breakout tape, which reading is more process-aware?',
      choices: [
        'The first tick beyond the range is a confirmed breakout',
        'A break needs acceptance and enough participation to trust a stop',
        'Stops never get filled in thin markets so they are free',
        'Volume is irrelevant',
      ],
      correctIndex: 1,
      explanation: 'Acceptance and participation are liquidity questions dressed as chart questions.',
      conceptId: 'liquidity',
      askEvidence: true,
      chart: {
        id: 'liq-ex',
        kind: 'breakout',
        title: 'Failed hold versus later acceptance',
        caption: 'Educational example — not a live market.',
      },
    },
    quiz: [
      mcq(
        'q1',
        'A wide spread most directly threatens…',
        [
          'Your RSI reading',
          'The honesty of entry, stop, and R:R',
          'The company’s earnings',
          'Your simulated starting cash label',
        ],
        1,
        [
          'RSI does not pay the spread.',
          'If you cannot transact near the level, the plan is fictional.',
          'Fundamentals are a different lesson.',
          'Paper cash is labelled simulated regardless of spread.',
        ],
        'liquidity',
      ),
    ],
    takeaways: ['Ask whether you can exit near invalidation.', 'Thin tapes inflate false breaks.'],
    practice: [PRACTICE_CHART, REPLAY],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'ta-macd',
    title: 'MACD: lagging momentum, not a crystal ball',
    description: 'MACD describes how two averages of price have been relating. Histogram expansion is persistence, not a buy alarm.',
    category: 'technical_analysis',
    difficulty: 'intermediate',
    durationMinutes: 14,
    sortOrder: 31,
    tags: ['macd', 'momentum', 'histogram'],
    searchKeywords: ['macd histogram', 'macd signal', 'momentum lag'],
    prerequisiteIds: ['ta-moving-averages', 'ta-trend-range'],
    relatedLessonIds: ['ta-rsi', 'ta-momentum', 'ta-divergence'],
    conceptIds: ['macd', 'momentum'],
    objectives: [
      'Read MACD as lagged momentum context.',
      'Refuse crossovers as automatic orders.',
    ],
    whyItMatters:
      'Crossover culture turns a descriptive tool into a slot machine. You need it as a second look at persistence — after structure.',
    explanation:
      'MACD is the difference between a faster and slower average of price, with a signal line on that difference. The histogram is how that gap is changing.\n\nBecause it is built from averages, it lags. In trends it can stay on one side of zero. That is persistence, not a bug. In ranges, whipsaws are the cost of using a trend tool.',
    chart: {
      id: 'macd-core',
      kind: 'macd',
      title: 'Histogram is persistence, not permission',
      caption: 'Educational MACD histogram. Not a live reading and not a trade instruction.',
      exercise: {
        prompt: 'A rising histogram during an already-labelled uptrend most usefully means…',
        choices: [
          'Buy more immediately',
          'Recent momentum has been persistent — still check structure and risk',
          'The move must reverse',
          'This is live broker data',
        ],
        correctIndex: 1,
        explanation: 'MACD lags price. Combine it with structure. Never let a crossover skip invalidation.',
      },
    },
    examples: [
      'Uptrend, MACD above zero: the tool agrees with the trend. That is not extra edge by itself.',
      'Range, repeated crossovers: the tool is describing chop, not handing you a system.',
    ],
    mistakes: ['Buying every bullish crossover.', 'Ignoring that MACD can stay positive in a trend like RSI can stay stretched.'],
    limitations: ['Settings are conventions. Changing them to fit the last move is curve-fitting.'],
    whenItFails: ['Choppy ranges.', 'Sudden news that averages cannot “see” in time.'],
    whenItWorks: ['As a confirmation question after you already named trend versus range.'],
    exercise: {
      id: 'ex-macd',
      kind: 'choose',
      prompt: 'Price is in a clear range. MACD flips bullish. Best process response?',
      choices: [
        'Market buy — the crossover is the edge',
        'Treat it as a noisy reading unless structure actually breaks and holds',
        'Double size because two indicators now agree',
        'Disable MACD forever',
      ],
      correctIndex: 1,
      explanation: 'Trend tools in ranges produce whipsaws. Structure first.',
      conceptId: 'macd',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'MACD stays above zero for many bars in an uptrend. This usually means…',
        [
          'An overdue short',
          'Lagged momentum has been one-sided — fading it needs more than the histogram',
          'A guaranteed continuation',
          'Volume must be falling',
        ],
        1,
        [
          'Overdue is not a method.',
          'Persistence can last. Process still needs invalidation.',
          'Nothing on the oscillator is a guarantee.',
          'MACD does not measure volume.',
        ],
        'macd',
      ),
    ],
    takeaways: ['MACD lags. That is the point and the cost.', 'Crossovers are not orders.'],
    practice: [{ ...PRACTICE_CHART, href: '/practice?drill=identify-trend' }, REPLAY],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'ta-false-breakouts',
    title: 'False breakouts: when the poke is not the point',
    description: 'A tick beyond a level is not acceptance. Failed breaks are common — especially without participation.',
    category: 'technical_analysis',
    difficulty: 'intermediate',
    durationMinutes: 15,
    sortOrder: 33,
    tags: ['breakout', 'false breakout', 'acceptance', 'failed break'],
    searchKeywords: ['why did my breakout fail', 'fakeout', 'false breakout', 'failed breakout'],
    prerequisiteIds: ['ta-structure', 'ta-trend-range', 'ta-volume'],
    relatedLessonIds: ['ta-volume', 'foundations-liquidity', 'dec-invalidation'],
    conceptIds: ['false-breakouts', 'breakouts'],
    objectives: [
      'Distinguish a poke from acceptance.',
      'List evidence that would make a break more trustworthy — without turning it into a guarantee.',
    ],
    whyItMatters:
      'Chasing the first tick beyond resistance is a common process error. The market often returns inside the range and tags stops.',
    explanation:
      'A breakout claim says: “price has accepted beyond a previously respected zone.” Acceptance usually looks like a close beyond, some holding on a retest, and participation that is not a single thin print.\n\nA false breakout is when that claim fails quickly. It is not proof of conspiracy. It is a reminder that levels are zones and that liquidity can run stops.',
    chart: {
      id: 'fb-core',
      kind: 'breakout',
      title: 'Failed hold, then a later attempt',
      caption: 'Educational example of a poke that does not hold, then a later retest. Not live data.',
    },
    examples: [
      'Close beyond resistance, immediate return inside, no volume expansion.',
      'Later: close beyond, pause, retest holds — still not a promise, but a better claim.',
    ],
    mistakes: [
      'Entering on the first tick through a round number.',
      'Moving the stop to breakeven instantly, then calling the failed break “bad luck” instead of premature entry.',
    ],
    limitations: ['No checklist removes false breaks. You can only improve the quality of the claim and the size.'],
    whenItFails: ['News gaps.', 'When you need the break to be real because you are already sized.'],
    whenItWorks: ['As a filter: wait for hold/retest, or size as if the first poke is a probe.'],
    exercise: {
      id: 'ex-fb',
      kind: 'identify',
      prompt: 'On this educational tape, which event is the failed break?',
      choices: [
        'The quiet bars inside the range',
        'The first marked break that does not hold',
        'The later retest/acceptance label',
        'The title of the chart',
      ],
      correctIndex: 1,
      explanation: 'The scene labels a break, a failed hold, then a later attempt. The failed hold is the false-break lesson.',
      conceptId: 'false-breakouts',
      askEvidence: true,
      chart: {
        id: 'fb-ex',
        kind: 'breakout',
        title: 'Name the failed hold',
        caption: 'Educational tape — not a live market.',
      },
    },
    quiz: [
      mcq(
        'q1',
        'A breakout is more trustworthy when…',
        [
          'The first tick beyond the level happens, even on low volume',
          'Price accepts beyond the zone and a retest does not immediately fail — still with risk defined',
          'Social media agrees',
          'You already bought, so it must work',
        ],
        1,
        [
          'The first tick is often the stop run.',
          'Acceptance is a claim you can still be wrong about — so size and invalidation remain.',
          'Crowds are not evidence.',
          'Sunk cost is not a method.',
        ],
        'false-breakouts',
      ),
      mcq(
        'q2',
        'Your breakout failed. The process question is…',
        [
          'How to get the loss back on the next ticker',
          'Whether entry was a poke, whether size matched uncertainty, and what you will require next time',
          'Which indicator to add',
          'Whether simulated P/L can be rewritten',
        ],
        1,
        [
          'Revenge trading is a psychology lesson — and a process failure.',
          'Review the claim quality, not the ego.',
          'More indicators rarely fix premature entry.',
          'The ledger is immutable. Review is the point.',
        ],
        'false-breakouts',
      ),
    ],
    takeaways: [
      'A poke is not acceptance.',
      'Failed breaks are normal. Premature size is optional.',
    ],
    practice: [{ label: 'Breakout quality drill', href: '/practice?drill=breakout-quality', description: 'Ask what would confirm a break.' }],
    simulation: [SIMULATE],
    replay: [replayEpisodeLink('false-breakout-drill', 'Name the failed hold before the next poke')],
  }),

  makeFlagshipLesson({
    id: 'ta-divergence',
    title: 'Divergence: a question, never a trigger',
    description: 'Price makes a new extreme while momentum does not. That is a research clue — not a market order.',
    category: 'technical_analysis',
    difficulty: 'intermediate',
    durationMinutes: 12,
    sortOrder: 34,
    tags: ['divergence', 'rsi', 'momentum'],
    searchKeywords: ['bearish divergence', 'bullish divergence', 'rsi divergence'],
    prerequisiteIds: ['ta-rsi', 'ta-structure'],
    relatedLessonIds: ['ta-rsi', 'ta-macd', 'ta-momentum'],
    conceptIds: ['divergence'],
    objectives: [
      'Define divergence without implying reversal certainty.',
      'List what else you would need before it changes size or bias.',
    ],
    whyItMatters:
      'Divergence is one of the most over-traded ideas. It feels like secret knowledge. It is only a mismatch between price and a derived oscillator.',
    explanation:
      'Bullish divergence: price lower low, oscillator higher low. Bearish: price higher high, oscillator lower high.\n\nIn a strong trend, divergence can print for a long time. The honest next step is to ask what would confirm (structure break, failed hold) and what would invalidate (trend resumes with participation).',
    chart: {
      id: 'div-rsi',
      kind: 'rsi',
      title: 'Stretch and washout — not a sell alarm',
      caption: 'Educational RSI. Divergence is a question you still have to locate on price.',
    },
    examples: [
      'New price high, weaker RSI high: ask if the advance is tiring — then check structure.',
      'Fading every divergence in a trend is a way to donate size.',
    ],
    mistakes: ['Shorting solely on bearish divergence.', 'Ignoring the timeframe of the swings you compared.'],
    limitations: ['Oscillator settings change where divergence appears. That is a warning, not a feature.'],
    whenItFails: ['Strong trends.', 'Comparing swings that are not actually related.'],
    exercise: {
      id: 'ex-div',
      kind: 'explain',
      prompt: 'In one or two sentences: what would you need besides RSI divergence before reducing risk or flipping bias?',
      minChars: 24,
      modelAnswer:
        'A change in price structure (break of a swing, failed hold) plus a defined invalidation. Divergence alone is not an order.',
      explanation: 'If your answer was only “wait for RSI to cross 50”, you still skipped structure and risk.',
      conceptId: 'divergence',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'Price makes a new high, RSI makes a lower high. You should…',
        [
          'Sell immediately',
          'Treat it as a clue and check structure, participation, and invalidation',
          'Ignore price',
          'Assume the data is fake',
        ],
        1,
        [
          'Immediate selling is a trigger addiction.',
          'Clues need a process, not a reflex.',
          'Price is the object of the decision.',
          'Educational charts are labelled. Live or sample, the logic is the same: don’t skip process.',
        ],
        'divergence',
      ),
    ],
    takeaways: ['Divergence is a mismatch, not a mandate.', 'Structure still decides whether the clue matters.'],
    practice: [{ ...PRACTICE_CHART, href: '/practice?drill=missing-evidence' }],
    simulation: [SIMULATE],
    journalHref: '/journal?from=academy',
  }),

  makeFlagshipLesson({
    id: 'ta-momentum',
    title: 'Momentum: speed of the recent move',
    description: 'Momentum describes how one-sided recent change has been. Strong momentum can stay strong. Weakening momentum is not automatically a reversal.',
    category: 'technical_analysis',
    difficulty: 'beginner',
    durationMinutes: 11,
    sortOrder: 30,
    tags: ['momentum', 'trend', 'rsi'],
    searchKeywords: ['what is momentum', 'strong trend', 'persistence'],
    prerequisiteIds: ['ta-trend-range'],
    relatedLessonIds: ['ta-rsi', 'ta-macd', 'dec-regime'],
    conceptIds: ['momentum'],
    objectives: [
      'Separate momentum from direction forecasts.',
      'Explain why overbought can persist.',
    ],
    whyItMatters:
      '“It went up too fast” is a feeling. Momentum tools try to describe that feeling. Used as sell signals, they fight persistence.',
    explanation:
      'If recent closes were persistently strong, oscillators look stretched. That can mean: the move is mature, or the trend is simply healthy.\n\nYou cannot know which from the oscillator alone. Combine with structure (are higher lows intact?) and your risk budget.',
    chart: {
      id: 'mom-rsi',
      kind: 'rsi',
      title: 'Why RSI can stay stretched',
      caption: 'Educational advance that keeps momentum high. Overbought ≠ sell.',
    },
    examples: [
      'RSI > 70 in a clean uptrend for weeks — fading it repeatedly is a process error.',
      'Momentum slowing while structure still holds: reduce eagerness, not necessarily reverse.',
    ],
    mistakes: ['Equating stretched with “must reverse now”.', 'Adding more oscillators until one agrees with your hope.'],
    limitations: ['Momentum lookbacks are arbitrary.'],
    whenItFails: ['Climaxes and gaps.', 'When you needed it to mean reverse.'],
    exercise: {
      id: 'ex-mom',
      kind: 'select',
      prompt: 'Why can RSI stay overbought in a trend?',
      choices: [
        'The indicator is broken',
        'Recent gains can remain persistently stronger than recent losses',
        'Brokers freeze RSI at 70',
        'Overbought is a legal sell order',
      ],
      correctIndex: 1,
      explanation: 'Stretched means one-sided recent action. Trends are allowed to be one-sided.',
      conceptId: 'momentum',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        '“Overbought” most honestly means…',
        [
          'Sell',
          'Recent upside was stretched relative to recent downside',
          'Price cannot go higher',
          'You found a secret signal',
        ],
        1,
        [
          'It is not a sell command.',
          'Description of recent one-sidedness.',
          'Prices can keep going.',
          'There is no secret. There is context.',
        ],
        'momentum',
      ),
    ],
    takeaways: ['Momentum can persist.', 'Stretched is a description, not an order.'],
    practice: [PRACTICE_CHART],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'risk-per-trade',
    title: 'Risk per trade: the 1% idea as a budget, not a slogan',
    description: 'Risk per trade is how much of equity you are willing to lose if invalidation hits. It is a budget. It is not a prediction of the loss.',
    category: 'risk_management',
    difficulty: 'beginner',
    durationMinutes: 12,
    sortOrder: 40,
    tags: ['risk', '1 percent', 'position sizing'],
    searchKeywords: ['risk per trade', 'how much to risk', '1% risk'],
    prerequisiteIds: ['basics-rr'],
    relatedLessonIds: ['risk-position-sizing', 'risk-ruin', 'risk-drawdown'],
    conceptIds: ['risk-per-trade', 'position-sizing'],
    objectives: [
      'Compute cash risk from equity × risk fraction.',
      'Refuse to let a “good idea” exceed the budget.',
    ],
    whyItMatters:
      'Without a budget, every chart becomes a negotiation with hope. The 1% example is a teaching rail — your plan can differ, but it must be explicit.',
    explanation:
      'Cash risk ≈ equity × risk percent. Quantity ≈ cash risk / distance to invalidation.\n\nIf you skip invalidation, you do not have risk per trade. You have a wish.',
    chart: {
      id: 'rr-visual',
      kind: 'risk_reward',
      title: 'Entry, stop, target — teaching sketch',
      caption: 'Educational R:R sketch. Distances teach size. They are not a live order ticket.',
    },
    examples: [
      '$100,000 paper equity, 1% risk, stop 2.00 away ⇒ 500 units (before fees).',
      'Halving risk in a volatile week is a process choice, not cowardice.',
    ],
    mistakes: ['Risking 1% “unless this one is special”.', 'Measuring risk from a random round number instead of invalidation.'],
    limitations: ['Gaps can exceed planned cash risk. Budget is not a guarantee.'],
    whenItWorks: ['Invalidation is written first, then cash risk is a cap — including on “obvious” ideas.'],
    whenItFails: ['Correlated positions that are secretly one bet.', 'Leverage (not used in TradeAcademy simulation v1).'],
    exercise: {
      id: 'ex-rpt',
      kind: 'calculate',
      prompt: 'Simulated equity 100,000. Risk 1%. Invalidation is 2.50 away from entry. Quantity?',
      expectedValue: 400,
      tolerance: 0.01,
      unit: 'units',
      explanation: '1,000 cash risk / 2.50 = 400. This is paper math, not a recommendation to trade.',
      conceptId: 'risk-per-trade',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'Risk per trade is…',
        [
          'How much you expect to make',
          'How much equity you accept losing if the thesis is wrong at the stop',
          'The indicator reading',
          'Simulated profit after a win',
        ],
        1,
        [
          'Target is not risk.',
          'Budget for being wrong.',
          'Indicators do not spend your cash.',
          'P/L is not the definition of planned risk.',
        ],
        'risk-per-trade',
      ),
    ],
    takeaways: ['No invalidation ⇒ no risk number.', 'Special ideas still pay the budget.'],
    practice: [PRACTICE_RR, { label: '1% size drill', href: '/practice?drill=position-size', description: 'Keep cash risk stable when the stop widens.' }],
    simulation: [{ ...SIMULATE, href: '/simulate' }],
    replay: [replayEpisodeLink('gold-regime-risk', 'Regime-risk room — budget first, then size')],
  }),

  makeFlagshipLesson({
    id: 'risk-stops',
    title: 'Stops: invalidation, not a hope line',
    description: 'A stop belongs where the thesis is wrong — usually beyond structure — not where the loss “feels OK”.',
    category: 'risk_management',
    difficulty: 'beginner',
    durationMinutes: 11,
    sortOrder: 41,
    tags: ['stop', 'invalidation', 'structure'],
    searchKeywords: ['stop loss', 'where to put stop', 'invalidation'],
    prerequisiteIds: ['ta-structure', 'risk-per-trade'],
    relatedLessonIds: ['dec-invalidation', 'risk-position-sizing', 'ta-false-breakouts'],
    conceptIds: ['invalidation', 'stop-logic'],
    objectives: [
      'Place a stop as thesis failure, then size to it.',
      'Avoid tightening a stop because of discomfort rather than new evidence.',
    ],
    whyItMatters:
      'Stops that are “nearby” for comfort get run. Stops that are “far” without size adjustment blow the budget. Structure first, size second.',
    explanation:
      'If your idea is “buyers still defend this zone”, invalidation is a decisive break and hold beyond that zone — not a one-tick poke if your plan says so.\n\nThen compute quantity so that distance × quantity ≈ planned cash risk.',
    chart: {
      id: 'stop-sr',
      kind: 'support_resistance',
      title: 'Invalidation lives relative to a zone',
      caption: 'Educational support zone. A stop inside the zone is often noise. Below acceptance is a different claim.',
    },
    examples: [
      'Long at support: invalidation is acceptance below the zone, then size.',
      'Moving a stop further because you “need room” without reducing size is increasing risk.',
    ],
    mistakes: ['Stop at a round number with no structure.', 'Widening after entry without a new thesis.'],
    limitations: ['Gaps can skip the stop. Plan for that in volatile names.'],
    whenItWorks: ['The stop is the thesis-killer, then quantity is whatever that distance allows.'],
    whenItFails: ['When the thesis was never written, so any stop is arbitrary.'],
    exercise: {
      id: 'ex-stop',
      kind: 'rank',
      prompt: 'Rank these stop reasons from most process-respecting to least.',
      items: [
        'Beyond the structure that would prove the thesis wrong, then size to that distance',
        'Wherever a 1% move happens to be, ignoring structure',
        'Wherever you would feel sad, regardless of the chart',
      ],
      correctOrder: [0, 1, 2],
      explanation: 'Thesis → structure → distance → size. Feelings and round percentages are not invalidation.',
      conceptId: 'stops',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'You should choose the stop first because…',
        [
          'Brokers require it',
          'Distance to invalidation determines quantity for a cash-risk budget',
          'It maximises simulated profit',
          'Indicators tell you the exact pip',
        ],
        1,
        [
          'This is an education app, not a broker.',
          'Size is the residual of risk and distance.',
          'Stops are not a profit engine.',
          'There is no exact pip of truth.',
        ],
        'stops',
      ),
    ],
    takeaways: ['Stop is where the idea dies.', 'Move size, not the story, when distance changes.'],
    practice: [
      PRACTICE_RR,
      {
        label: 'Name the thesis-killer',
        href: '/practice?drill=name-invalidation',
        description: 'A feeling is not invalidation.',
      },
      JOURNAL,
    ],
    simulation: [SIMULATE],
    replay: [replayEpisodeLink('failed-setup-patience', 'Write the killer, then skip if the case is not there')],
  }),

  makeFlagshipLesson({
    id: 'risk-drawdown',
    title: 'Drawdown: peak to trough, not a skill score',
    description: 'Drawdown is how far equity has fallen from its peak. It measures pain and survival — it does not tell you if the last decision was high quality.',
    category: 'risk_management',
    difficulty: 'beginner',
    durationMinutes: 10,
    sortOrder: 44,
    tags: ['drawdown', 'equity', 'peak'],
    searchKeywords: ['what does drawdown actually mean', 'max drawdown', 'peak equity'],
    prerequisiteIds: ['risk-per-trade'],
    relatedLessonIds: ['risk-expectancy', 'risk-ruin', 'port-diversification'],
    conceptIds: ['drawdown'],
    objectives: [
      'Compute drawdown as (equity − peak) / peak.',
      'Refuse to treat a lucky equity high as proof of process.',
    ],
    whyItMatters:
      'People either ignore drawdown until it is a crisis, or they use it to shame themselves. Both miss the point: survival and whether risk per trade was honest.',
    explanation:
      'Peak equity is the highest equity so far. Current drawdown is negative or zero. Max drawdown is the worst of those readings.\n\nA high-quality process can still draw down. A reckless process can still print a green month. Simulated equity in TradeAcademy is paper — still useful for practising the math.',
    examples: [
      'Peak 110,000, equity 100,000 ⇒ about −9.1% current drawdown.',
      'A 5% drawdown challenge is a process constraint, not a trophy for 0% ever.',
    ],
    mistakes: ['Increasing size to “get back to peak”.', 'Calling a drawdown proof you cannot learn.'],
    limitations: ['Paper drawdown ≠ live path dependence with emotions and withdrawals.'],
    whenItFails: ['When correlated bets make “1% per trade” into 8% the same day.'],
    exercise: {
      id: 'ex-dd',
      kind: 'calculate',
      prompt: 'Peak equity 11,000. Current equity 10,000. Drawdown as a percent of peak (negative number, one decimal as −9.1 if you round to tenths of a percent)? Enter the percent magnitude: 9.1',
      expectedValue: 9.1,
      tolerance: 0.15,
      unit: '%',
      explanation: '(10000 − 11000) / 11000 = −9.09% ≈ 9.1% magnitude. Formula uses peak, not starting cash.',
      conceptId: 'drawdown',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'Drawdown is measured from…',
        [
          'Starting cash only',
          'Peak equity to current equity',
          'The last winning trade',
          'RSI',
        ],
        1,
        [
          'Starting cash is for total return, a different ratio.',
          'Peak-to-trough is the definition used in the simulation engine.',
          'Trades are not the peak unless they made a new high.',
          'Oscillators are not equity.',
        ],
        'drawdown',
      ),
    ],
    takeaways: ['Drawdown is survival math.', 'It does not grade a single thesis.'],
    practice: [JOURNAL, { ...SIMULATE, description: 'Watch current and max drawdown on the paper account. Do not chase the peak.' }],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'risk-ruin',
    title: 'Risk of ruin: why small edges still die',
    description: 'If losses can cluster, a large bet size can wipe the account even with a “positive expectancy” story. Ruin is a size problem.',
    category: 'risk_management',
    difficulty: 'intermediate',
    durationMinutes: 12,
    sortOrder: 46,
    tags: ['ruin', 'expectancy', 'size'],
    searchKeywords: ['risk of ruin', 'blow up', 'too large'],
    prerequisiteIds: ['risk-per-trade', 'risk-expectancy'],
    relatedLessonIds: ['risk-drawdown', 'psych-loss-aversion', 'port-diversification'],
    conceptIds: ['risk-of-ruin'],
    objectives: [
      'Explain ruin as path + size, not as “bad luck only”.',
      'Connect clustered losses and correlation to faster ruin.',
    ],
    whyItMatters:
      'Expectancy without a survival constraint is a spreadsheet fantasy. The teaching point is: smaller, repeating risk beats heroic size.',
    explanation:
      'Even a method with a positive average can see long losing streaks. If each loss is 20% of equity, a short streak ends the game. If each loss is 0.5–1%, you still have a process to review.\n\nCorrelation makes several “1% trades” into one fat bet.',
    examples: [
      'Five uncorrelated 1% losses vs five names in the same theme — different ruin paths.',
      'Paper account: the 1% challenge exists to practise the constraint, not to brag.',
    ],
    mistakes: ['Raising size after losses to recover faster.', 'Assuming a backtest average forbids streaks.'],
    limitations: ['We are not computing a full ruin formula here. We are teaching the shape of the problem.'],
    whenItFails: ['When leverage is added (not in current simulation).', 'When you cannot actually take the planned stop.'],
    exercise: {
      id: 'ex-ruin',
      kind: 'compare',
      prompt: 'Which book is closer to ruin, holding “edge” stories equal?',
      leftLabel: '10% of equity at risk each decision, correlated names',
      rightLabel: '1% of equity, uncorrelated enough that clusters are smaller',
      correctIndex: 1,
      explanation: 'Ruin cares about the size of the hole you can fall into, not the slogan on the backtest.',
      conceptId: 'risk-of-ruin',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'A method can have positive expectancy and still be ruined if…',
        [
          'RSI is overbought',
          'Bet size and clustered losses are large relative to equity',
          'You journal too much',
          'You use paper trading',
        ],
        1,
        [
          'Oscillators are unrelated to ruin math.',
          'Path and size dominate slogans.',
          'Journaling is part of review, not ruin.',
          'Paper trading is how we practise without real ruin — the math still teaches.',
        ],
        'risk-of-ruin',
      ),
    ],
    takeaways: ['Edge without a cap on loss size is incomplete.', 'Correlation is hidden size.'],
    practice: [PRACTICE_RR],
    simulation: [SIMULATE],
  }),
];
