import { makeFlagshipLesson, replayEpisodeLink } from './lesson-factory';
import type { Lesson } from '../types/academy.types';
import {
  BRIGHTCANVAS,
  CEDAR_RETAIL,
  FUNDAMENTAL_SAMPLE_DISCLAIMER,
  HARBOR_COMPONENTS,
  NORTHLINE_UTILITIES,
  formatCompanyCard,
  formatCompanyPair,
} from './fundamental-cases';

const SIMULATE = {
  label: 'Apply in paper trading',
  href: '/simulate',
  description: 'SIMULATED TRADING. Process first. Simulated P/L is not the grade.',
};

const JOURNAL = {
  label: 'Journal the reasoning',
  href: '/journal?from=academy',
  description: 'Write what happened versus what you expected. Do not grade yourself on paper P/L.',
};

const PRACTICE = {
  label: 'Practice this skill',
  href: '/practice',
  description: 'Short drill. The answer is the reasoning.',
};

function mcq(
  id: string,
  prompt: string,
  choices: string[],
  correctIndex: number,
  choiceExplanations: string[],
  conceptId: string,
): Lesson['quiz'][number] {
  return {
    id,
    prompt,
    choices,
    correctIndex,
    explanation: choiceExplanations[correctIndex] ?? '',
    choiceExplanations,
    conceptId,
  };
}

export const FLAGSHIP_PROCESS_LESSONS: Lesson[] = [
  makeFlagshipLesson({
    id: 'risk-exposure',
    title: 'Exposure: how much of you is in the market',
    description: 'Exposure is capital tied to open risk — not the same as “I like the story”. Concentration is when one name dominates that exposure.',
    category: 'portfolio',
    difficulty: 'intermediate',
    durationMinutes: 11,
    sortOrder: 50,
    tags: ['exposure', 'concentration', 'allocation'],
    searchKeywords: ['portfolio exposure', 'how much invested', 'concentration'],
    prerequisiteIds: ['risk-per-trade'],
    relatedLessonIds: ['port-diversification', 'dec-portfolio-risk', 'risk-correlation'],
    conceptIds: ['concentration-risk'],
    objectives: [
      'Distinguish cash, invested, and equity.',
      'Treat a 20%+ single-name weight as a process observation, not a badge.',
    ],
    whyItMatters:
      'People track P/L and ignore that one position became the whole book. Simulation shows portfolio weight for this reason.',
    explanation:
      'Invested amount is mark-to-market of open positions. Equity is cash plus that. Portfolio weight is position value / equity.\n\nHigh weight means the next decision is mostly that name — including its gap and news risk.',
    examples: [
      'Paper book: 20% in one equity is the diversification challenge’s teaching rail.',
      'Three tech names that all move together are not three independent exposures.',
    ],
    mistakes: ['Calling a concentrated book “high conviction” without measuring it.', 'Adding to a winner until it is the account.'],
    limitations: ['Weight is a snapshot. Correlation can make “diversified” weights still one bet.'],
    whenItFails: ['When you only look at count of tickers, not weights and themes.'],
    exercise: {
      id: 'ex-exp',
      kind: 'calculate',
      prompt: 'Equity 100,000. One position worth 25,000. What is that name’s portfolio weight as a percent?',
      expectedValue: 25,
      tolerance: 0.05,
      unit: '%',
      explanation: '25,000 / 100,000 = 25%. That already exceeds a 20% diversification teaching rail.',
      conceptId: 'exposure',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'A 40% weight in one name means…',
        [
          'You are well diversified',
          'That name dominates both the upside story and the next drawdown',
          'Risk per trade must be 40%',
          'The simulation is live brokerage',
        ],
        1,
        [
          'Count of tickers is not diversification.',
          'Concentration is a process fact.',
          'Risk per trade is a different budget.',
          'Paper trading stays labelled simulated.',
        ],
        'concentration',
      ),
    ],
    takeaways: ['Weight is a decision, even if you never “decided”.', 'Concentration is measurable.'],
    practice: [PRACTICE],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'risk-correlation',
    title: 'Correlation: when many names are one bet',
    description: 'Correlation is how similarly two holdings move. Diversification that ignores it is a costume.',
    category: 'portfolio',
    difficulty: 'intermediate',
    durationMinutes: 11,
    sortOrder: 51,
    tags: ['correlation', 'diversification', 'theme'],
    searchKeywords: ['correlation', 'same theme', 'hidden concentration'],
    prerequisiteIds: ['risk-exposure', 'foundations-asset-classes'],
    relatedLessonIds: ['port-diversification', 'risk-ruin', 'dec-portfolio-risk'],
    conceptIds: ['correlation'],
    objectives: [
      'Spot theme risk (sector, factor, crypto-beta).',
      'Reduce size when several positions share a driver.',
    ],
    whyItMatters:
      'A “diversified” list of five growth stocks can be one interest-rate bet. Ruin math cares about that.',
    explanation:
      'If two names usually rise and fall together, their combined weight is the real exposure.\n\nYou do not need a perfect coefficient. You need an honest sentence: “What would hurt all of these at once?”',
    examples: [
      'Banks + insurers in the same rate shock.',
      'BTC and a high-beta crypto equity in a risk-off tape.',
    ],
    mistakes: ['Assuming different tickers equal different risks.', 'Adding a correlated name to “diversify” a losing theme.'],
    limitations: ['Correlation changes in crises — often toward 1.'],
    whenItFails: ['When the shared driver is something you did not name (liquidity, USD, regulation).'],
    exercise: {
      id: 'ex-corr',
      kind: 'scenario',
      situation: 'You hold three semiconductor names, each 8% of equity.',
      prompt: 'The honest exposure statement is…',
      choices: [
        '24% in three independent stories',
        'About 24% in a shared semiconductor / risk-appetite theme unless proven otherwise',
        'Zero risk because each was a separate thesis',
        'Automatically safer than one 8% position',
      ],
      correctIndex: 1,
      explanation: 'Add weights when the driver is shared. Independence must be argued, not assumed.',
      conceptId: 'correlation',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'Correlation matters because…',
        [
          'It predicts next week’s winner',
          'Several 1% risks can become one large hole',
          'It replaces a stop',
          'It makes simulated fees',
        ],
        1,
        [
          'Correlation is not a crystal ball.',
          'Hidden size is the teaching point.',
          'Stops still belong on each thesis.',
          'Fees are unrelated.',
        ],
        'correlation',
      ),
    ],
    takeaways: ['Ask what hurts all holdings at once.', 'Ticker count is not diversification.'],
    practice: [JOURNAL],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'psych-fomo',
    title: 'FOMO: the missing-move feeling',
    description: 'FOMO is acting because others got a move, not because your evidence and invalidation are ready.',
    category: 'psychology',
    difficulty: 'beginner',
    durationMinutes: 10,
    sortOrder: 60,
    tags: ['fomo', 'chase', 'psychology'],
    searchKeywords: ['fomo', 'chasing', 'fear of missing out'],
    prerequisiteIds: ['dec-psychology'],
    relatedLessonIds: ['psych-revenge', 'ta-false-breakouts', 'dec-why-not'],
    conceptIds: ['fomo'],
    objectives: [
      'Recognise chase behaviour in yourself.',
      'Replace “I missed it” with a skip rule.',
    ],
    whyItMatters:
      'Chasing late breakouts and stretched momentum is how FOMO spends the risk budget. The market does not owe you the move you watched.',
    explanation:
      'FOMO feels urgent. Process is slow: thesis, evidence, invalidation, size.\n\nIf the only new information is that price already went, you do not have a new thesis — you have a feeling.',
    chart: {
      id: 'fomo-break',
      kind: 'breakout',
      title: 'Late chase versus wait-for-hold',
      caption: 'Educational poke. Chasing the first tick is a FOMO pattern, not a method.',
    },
    examples: [
      'Buying the close of a vertical day because a chat room is loud.',
      'Skipping and writing why-not is a complete decision.',
    ],
    mistakes: ['Increasing size because you “already missed the easy part”.', 'Abandoning stops to stay in the story.'],
    limitations: ['You will still miss moves. That is not a process error by itself.'],
    whenItWorks: ['You notice the urgency, write why-not, and keep size at zero until a killable thesis exists.'],
    whenItFails: ['When your playbook actually requires momentum continuation — then write that in advance, with size that survives being late.'],
    exercise: {
      id: 'ex-fomo',
      kind: 'choose',
      prompt: 'Price already ran. You have no pre-written thesis. Best next action?',
      choices: [
        'Market buy so you are not left behind',
        'Stand aside, optionally journal the skip, wait for a plan that includes invalidation',
        'Double size on the next ticker',
        'Turn off labels that say SIMULATED',
      ],
      correctIndex: 1,
      explanation: 'Missing a move is cheap. An unplanned chase is how books get hurt.',
      conceptId: 'fomo',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'FOMO decisions are characterised by…',
        [
          'A written invalidation prepared before the impulse',
          'Urgency from a move already in motion, with weak evidence',
          'Smaller size than usual',
          'Waiting for a retest',
        ],
        1,
        [
          'Written invalidation is the opposite of FOMO.',
          'Urgency + weak evidence is the pattern.',
          'FOMO often increases size.',
          'Waiting for a retest is usually more process-like.',
        ],
        'fomo',
      ),
    ],
    takeaways: ['A missed move is not a loss of self-worth.', 'No thesis, no trade — including paper trades.'],
    practice: [
      {
        label: 'FOMO chase drill',
        href: '/practice?drill=fomo-chase',
        description: 'Urgency from a move already in motion is not a thesis.',
      },
      JOURNAL,
    ],
    simulation: [SIMULATE],
    replay: [replayEpisodeLink('gamestop-squeeze', 'Crowd-pressure room — skip is a complete decision')],
  }),

  makeFlagshipLesson({
    id: 'psych-revenge',
    title: 'Revenge trading: trying to make the market apologise',
    description: 'Revenge is sizing or frequency driven by a prior loss, not by a new independent decision.',
    category: 'psychology',
    difficulty: 'beginner',
    durationMinutes: 9,
    sortOrder: 61,
    tags: ['revenge', 'tilt', 'psychology'],
    searchKeywords: ['revenge trading', 'get it back', 'tilt'],
    prerequisiteIds: ['dec-psychology'],
    relatedLessonIds: ['psych-fomo', 'psych-loss-aversion', 'risk-per-trade'],
    conceptIds: ['revenge-trading'],
    objectives: [
      'Name revenge as a size/frequency problem.',
      'Use a pause rule after a plan break.',
    ],
    whyItMatters:
      'The second trade after a loss often has the worst process: larger size, worse location, no new evidence.',
    explanation:
      'A loss can be a correct process with a losing outcome. Revenge treats the market as an opponent who owes you.\n\nPaper trading still trains this. If you slam size after a red simulated fill, the lesson is the same.',
    examples: [
      'Stopped out, immediately re-enter twice as large.',
      'Protocol: after a rule break, no new risk until a journal sentence exists.',
    ],
    mistakes: ['“I know this ticker now.”', 'Disabling the stop because it “wasn’t fair”.'],
    limitations: ['Feelings happen. The skill is not acting them out with size.'],
    whenItWorks: ['After a plan break you pause, journal one sentence, and reset to planned size before any new risk.'],
    whenItFails: ['When you relabel revenge as “aggressiveness”.'],
    exercise: {
      id: 'ex-rev',
      kind: 'explain',
      prompt: 'Write the pause rule you want after a loss that broke your plan (one sentence).',
      minChars: 20,
      modelAnswer:
        'No new simulated or live risk until I journal what broke and reset to planned size.',
      explanation: 'If your rule still allows immediate double-size, it is not a pause rule.',
      conceptId: 'revenge-trading',
    },
    quiz: [
      mcq(
        'q1',
        'After a loss, increasing size because you “need it back” is…',
        [
          'Good expectancy management',
          'Revenge — risk is now about emotion, not the new thesis',
          'Required in challenges',
          'Proof the last stop was wrong',
        ],
        1,
        [
          'Expectancy assumes independent, sized bets — not chasing.',
          'Name it so you can interrupt it.',
          'Challenges measure process caps, not recovery speed.',
          'Stops can be correct and still lose.',
        ],
        'revenge-trading',
      ),
    ],
    takeaways: ['Outcome and process are different.', 'Pause rules are part of risk.'],
    practice: [
      {
        label: 'Revenge interrupt drill',
        href: '/practice?drill=revenge-interrupt',
        description: 'The second trade after a loss is often the worst file.',
      },
      JOURNAL,
    ],
    simulation: [SIMULATE],
    replay: [replayEpisodeLink('failed-setup-patience', 'Stand down after a failed idea — do not chase size')],
  }),

  makeFlagshipLesson({
    id: 'psych-loss-aversion',
    title: 'Loss aversion: why scratches feel worse than they are',
    description: 'Losses sting more than equal gains please. That can freeze exits and turn small invalidations into large ones.',
    category: 'psychology',
    difficulty: 'intermediate',
    durationMinutes: 10,
    sortOrder: 62,
    tags: ['loss aversion', 'psychology', 'exit'],
    searchKeywords: ['loss aversion', 'cannot take a loss', 'hold losers'],
    prerequisiteIds: ['dec-psychology', 'risk-stops'],
    relatedLessonIds: ['psych-overconfidence', 'dec-invalidation'],
    conceptIds: ['loss-aversion'],
    objectives: [
      'Notice the urge to move stops further from price after a loss starts.',
      'Pre-commit exit language in the thesis.',
    ],
    whyItMatters:
      'If invalidation is “I’ll know it when I feel it”, you will know it too late. Loss aversion buys time with your risk budget.',
    explanation:
      'A planned scratch is a success of process. An unplanned hold because it “might come back” is a different trade.\n\nWrite the exit as a condition, not a mood.',
    examples: [
      'Thesis invalidation hit; you wait for breakeven. That wait is a new decision with no size plan.',
      'Journal prompt: “Did I follow the exit I wrote?” — not “was I profitable?”',
    ],
    mistakes: ['Moving stops only when losing.', 'Taking winners instantly and holding losers “until they work”.'],
    limitations: ['Not every hold is loss aversion — sometimes the plan was time-based. Write that in advance.'],
    whenItFails: ['When you use “I’m a long-term investor” as an excuse for a broken short-term thesis.'],
    exercise: {
      id: 'ex-la',
      kind: 'select',
      prompt: 'Which behaviour is the textbook loss-aversion leak?',
      choices: [
        'Exiting at the written invalidation and journaling',
        'Widening the stop after price goes against you so you do not have to book the loss',
        'Reducing size because volatility rose, as planned',
        'Skipping a name with no thesis',
      ],
      correctIndex: 1,
      explanation: 'Changing the stop to avoid the feeling of a loss is a new, usually worse, trade.',
      conceptId: 'loss-aversion',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'A scratch at invalidation should be reviewed as…',
        [
          'Personal failure',
          'Process followed — now inspect whether the thesis was clear',
          'Proof you should not use stops',
          'A reason to double the next paper trade',
        ],
        1,
        [
          'Feelings are allowed. They are not the grade.',
          'Quality is adherence plus learning, not P/L.',
          'Stops are how invalidation becomes real.',
          'That is revenge.',
        ],
        'loss-aversion',
      ),
    ],
    takeaways: ['Write the exit before the sting.', 'A scratch can be high-quality.'],
    practice: [JOURNAL],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'psych-confirmation',
    title: 'Confirmation bias: collecting agreement',
    description: 'Confirmation bias is hunting for evidence that you are already right, and skipping what would hurt the idea.',
    category: 'psychology',
    difficulty: 'beginner',
    durationMinutes: 10,
    sortOrder: 63,
    tags: ['confirmation bias', 'evidence', 'psychology'],
    searchKeywords: ['confirmation bias', 'only seeing support', 'disagreeing evidence'],
    prerequisiteIds: ['dec-research-filter'],
    relatedLessonIds: ['dec-thesis', 'psych-overconfidence', 'dec-why-not'],
    conceptIds: ['confirmation-bias'],
    objectives: [
      'Force at least one disagreeing fact before size.',
      'Treat “I knew it” after a win as a warning, not a skill.',
    ],
    whyItMatters:
      'A thesis with only friendly indicators is a mood board. Decision quality needs what would prove you wrong.',
    explanation:
      'Before you size — even in simulation — write: evidence for, evidence against, what would invalidate.\n\nIf you cannot name against, you are not researching. You are decorating.',
    examples: [
      'Long thesis, only bullish RSI comments, ignored failed hold on volume.',
      'Practice drill “missing evidence” exists for this exact leak.',
    ],
    mistakes: ['Adding indicators until one agrees.', 'Unfollowing people who disagree rather than stressing the idea.'],
    limitations: ['You still must decide. The point is a fairer file, not endless doubt.'],
    whenItWorks: ['You write one disagreeing fact before size, and you would actually use it for the stop.'],
    whenItFails: ['When “against” is a token sentence you do not actually use for the stop.'],
    exercise: {
      id: 'ex-cb',
      kind: 'rank',
      prompt: 'Rank these research habits from strongest process to weakest.',
      items: [
        'Write for, against, and invalidation before any simulated size',
        'Skim only sources that already like the ticker',
        'Size first, then search for a story that fits the fill',
      ],
      correctOrder: [0, 1, 2],
      explanation: 'Evidence before size. Agreement-hunting is weaker. Story-after-fill is not research.',
      conceptId: 'confirmation-bias',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'The most useful question under confirmation bias is…',
        [
          'Who else is long?',
          'What evidence would make this idea wrong?',
          'How do I make RSI agree?',
          'How do I hide the paper loss?',
        ],
        1,
        [
          'Crowds are not invalidation.',
          'That is the core habit.',
          'Forcing agreement is the bias.',
          'The ledger stays. Review it.',
        ],
        'confirmation-bias',
      ),
    ],
    takeaways: ['Against-evidence is part of the thesis.', 'Wins can still be biased.'],
    practice: [
      { label: 'Confirmation-bias drill', href: '/practice?drill=confirmation-bias', description: 'Protecting a story is the leak, not the P/L.' },
      { label: 'Missing evidence drill', href: '/practice?drill=missing-evidence', description: 'Notice what is not in the file.' },
    ],
    simulation: [SIMULATE],
    replay: [replayEpisodeLink('failed-setup-patience', 'A tempting structure still needs contrary evidence')],
  }),

  makeFlagshipLesson({
    id: 'psych-overconfidence',
    title: 'Overconfidence: a hot streak is not a new edge',
    description: 'Overconfidence is raising complexity or size because recent outcomes were kind — not because the process improved.',
    category: 'psychology',
    difficulty: 'intermediate',
    durationMinutes: 9,
    sortOrder: 64,
    tags: ['overconfidence', 'size', 'psychology'],
    searchKeywords: ['overconfidence', 'hot streak', 'too much size'],
    prerequisiteIds: ['dec-psychology', 'risk-per-trade'],
    relatedLessonIds: ['psych-recency', 'risk-ruin'],
    conceptIds: ['overconfidence'],
    objectives: [
      'Keep risk percent stable unless the written plan changes it.',
      'Review winners with the same questions as losers.',
    ],
    whyItMatters:
      'Drawdowns often start after a green patch, when size quietly inflates. Paper trading makes that visible without real-money harm — still take it seriously.',
    explanation:
      'Process quality is about the file: thesis, size, invalidation, review. A streak is a path. It is not permission.\n\nIf you cannot explain the size increase in the plan, it is overconfidence.',
    examples: [
      'Three simulated wins, then 3× size “because I’m in sync”.',
      'Premium-feeling UI is not an edge. This academy is not a signal feed.',
    ],
    mistakes: ['Skipping journals on winners.', 'Adding markets you have not studied because “it’s working”.'],
    limitations: ['Confidence in a practiced skill is allowed. Unmeasured size jumps are not the same thing.'],
    whenItWorks: ['Risk percent stays in the plan after a green patch, and winners get the same journal questions as losers.'],
    whenItFails: ['When markets changed and the streak was regime luck.'],
    exercise: {
      id: 'ex-oc',
      kind: 'compare',
      prompt: 'After four paper wins, which response is process?',
      leftLabel: 'Triple size; skip the next journal',
      rightLabel: 'Keep planned risk; journal the winner like a loser',
      correctIndex: 1,
      explanation: 'Winners need review. Size changes belong in the plan, not in the mood.',
      conceptId: 'overconfidence',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'A simulated winning streak proves…',
        [
          'You should trade real money immediately',
          'Nothing automatic about next-trade quality — review the files',
          'Risk of ruin disappeared',
          'FOMO was correct',
        ],
        1,
        [
          'Paper is practice, not a graduation certificate.',
          'Path ≠ permission.',
          'Ruin still cares about the next cluster.',
          'Streaks do not justify chasing.',
        ],
        'overconfidence',
      ),
    ],
    takeaways: ['Streaks are not a plan.', 'Review winners.'],
    practice: [
      {
        label: 'Confidence-check drill',
        href: '/practice?drill=confidence-check',
        description: 'A paper streak is a path, not permission to inflate size.',
      },
      JOURNAL,
    ],
    simulation: [SIMULATE],
    replay: [replayEpisodeLink('failed-setup-patience', 'Feeling sharp is not a reason to force the next idea')],
  }),

  makeFlagshipLesson({
    id: 'psych-recency',
    title: 'Recency bias: the last tape feels like the only tape',
    description: 'Recency bias overweight the last few outcomes. Yesterday’s trend becomes today’s identity.',
    category: 'psychology',
    difficulty: 'intermediate',
    durationMinutes: 9,
    sortOrder: 65,
    tags: ['recency', 'regime', 'psychology'],
    searchKeywords: ['recency bias', 'last trade', 'regime change'],
    prerequisiteIds: ['dec-regime', 'dec-psychology'],
    relatedLessonIds: ['psych-overconfidence', 'ta-mtf'],
    conceptIds: ['recency-bias'],
    objectives: [
      'Separate “what just happened” from “what my playbook requires”.',
      'Re-check regime instead of cloning the last winner.',
    ],
    whyItMatters:
      'After a trend day, people fade every dip. After a chop day, they fade every break. Both can be recency, not reading.',
    explanation:
      'Ask: is the current structure still the same question? If not, the last fill is trivia.\n\nA journal that only lists the last three trades will bake recency in. Look at the sample of similar setups, not the mood of this morning.',
    examples: [
      'One failed breakout → never taking breaks again this month.',
      'One clean trend day → abandoning range rules.',
    ],
    mistakes: ['Changing the whole playbook after one outcome.', 'Using a tiny recent sample as “my edge”.'],
    limitations: ['Markets do change. Recency is ignoring the check, not noticing change.'],
    whenItFails: ['When you refuse to update a broken playbook because “in 2019 it worked” — that is the opposite bias. Still use evidence.'],
    exercise: {
      id: 'ex-rec',
      kind: 'scenario',
      situation: 'Yesterday a breakout failed. Today a different name shows a close beyond a range with a hold on retest.',
      prompt: 'Recency would push you to…',
      choices: [
        'Evaluate today’s evidence on its own file',
        'Skip automatically because yesterday hurt',
        'Size 3× to “make back” yesterday',
        'Ignore structure because MACD is green',
      ],
      correctIndex: 1,
      explanation: 'The question asked what recency would push — automatic skip from yesterday’s pain. Process would still open a new file.',
      conceptId: 'recency-bias',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'The antidote to recency is…',
        [
          'Only remember winners',
          'A written playbook plus a regime check, not the last tick’s mood',
          'More screens',
          'Deleting the journal',
        ],
        1,
        [
          'That is another bias.',
          'Rules and regime beat vibes.',
          'Screens do not fix sampling.',
          'Journals are how you see the sample.',
        ],
        'recency-bias',
      ),
    ],
    takeaways: ['Last outcome is one data point.', 'Regime is a question you re-ask.'],
    practice: [PRACTICE, JOURNAL],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'psych-discipline',
    title: 'Discipline: doing the boring file',
    description: 'Discipline is repeating thesis, size, invalidation, and review — especially when nothing exciting is happening.',
    category: 'psychology',
    difficulty: 'beginner',
    durationMinutes: 8,
    sortOrder: 66,
    tags: ['discipline', 'process', 'checklist'],
    searchKeywords: ['trading discipline', 'stick to plan', 'checklist'],
    prerequisiteIds: ['dec-journaling'],
    relatedLessonIds: ['psych-fomo', 'dec-quality', 'risk-per-trade'],
    conceptIds: ['discipline'],
    objectives: [
      'Treat the pre-trade checklist as part of risk.',
      'Count skipped trades as decisions.',
    ],
    whyItMatters:
      'Education fails when it stays as reading. Discipline is the bridge into Practice, Simulation, and Journal.',
    explanation:
      'You will not feel like journaling a scratch. That is when the loop matters.\n\nTradeAcademy’s simulation challenges (thesis required, 1% risk, concentration, drawdown) exist to practise constraints — not to gamify P/L.',
    examples: [
      'No thesis, no simulated buy in the discipline challenge.',
      'Marking a lesson Practiced only after you open the drill or paper ticket.',
    ],
    mistakes: ['Bingeing lessons without a single drill.', 'Resetting the paper account to hide a process mess without reviewing it.'],
    limitations: ['Streaks of “discipline days” are a reminder, not XP. Missing a day is not moral failure.'],
    whenItFails: ['When discipline becomes rigidity: refusing to update a playbook that evidence killed.'],
    exercise: {
      id: 'ex-disc',
      kind: 'choose',
      prompt: 'Which sequence matches TradeAcademy’s loop?',
      choices: [
        'Trade first, maybe read later if you win',
        'Understand → see → practice → apply in simulation → review in journal',
        'Collect signals until one is green',
        'Maximise paper profit, then learn',
      ],
      correctIndex: 1,
      explanation: 'The product loop is Learn → Practice → Simulate → Review → Improve. P/L is not the grade.',
      conceptId: 'discipline',
    },
    quiz: [
      mcq(
        'q1',
        'Discipline in this app is mainly…',
        [
          'Never missing a candle',
          'Repeating a written decision file and review',
          'Trading every hour',
          'Chasing simulated equity highs',
        ],
        1,
        [
          'Attention ≠ discipline.',
          'The file is the skill.',
          'Frequency is not virtue.',
          'Paper highs are not mastery.',
        ],
        'discipline',
      ),
    ],
    takeaways: ['Skips count.', 'Review is part of the trade.'],
    practice: [{ label: 'Open the pre-trade checklist', href: '/academy/checklist/pre-trade-checklist' }, JOURNAL],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'fund-statements',
    title: 'Financial statements: the business, not the candle',
    description: 'Revenue, earnings, margins, cash flow, and the balance sheet describe a business. They do not tell you what the next candle will do.',
    category: 'fundamental_analysis',
    difficulty: 'beginner',
    durationMinutes: 14,
    sortOrder: 70,
    tags: ['revenue', 'earnings', 'margins', 'cash flow', 'balance sheet'],
    searchKeywords: ['earnings', 'revenue', 'cash flow', 'balance sheet', 'margins'],
    prerequisiteIds: ['fund-basics'],
    relatedLessonIds: ['fund-valuation-quality', 'fund-calendar', 'fund-economy'],
    conceptIds: ['revenue-growth', 'earnings', 'balance-sheet'],
    objectives: [
      'Map each statement to a question (growth, profitability, cash, obligations).',
      'Interpret changing margins and cash conversion without treating a beat as a long.',
      'Refuse to treat a simplified company file as an investment recommendation.',
    ],
    whyItMatters:
      'Price can ignore a “good” print. Fundamentals change what you think you own. They do not replace invalidation.',
    explanation:
      'Income statement: revenue and earnings and margins. Cash flow: whether earnings became cash. Balance sheet: what is owed and owned.\n\nA company can show earnings while burning cash. That is a different risk than a chart pattern.',
    examples: [
      'Revenue up, margins down: growth that is getting less efficient.',
      'Earnings beat, guidance poor, gap down — the tape is not obligated to celebrate.',
    ],
    mistakes: ['Equating EPS beat with a buy signal.', 'Ignoring debt because the chart is pretty.'],
    limitations: ['Statements are lagged and accounting-based. Fraud and one-offs exist.', FUNDAMENTAL_SAMPLE_DISCLAIMER],
    whenItWorks: [
      'You map growth, profitability, cash, and obligations as separate questions, then decide whether the file even deserves size.',
    ],
    whenItFails: ['When the driver is liquidity or a meme, not the business. Then say so — and size as speculation, if at all.'],
    exercise: {
      id: 'ex-fs-recognize',
      kind: 'select',
      prompt: 'Which statement is the first place to look for leverage and cash buffers?',
      choices: ['The income statement only', 'The balance sheet', 'A single candle', 'The P/E ratio alone'],
      correctIndex: 1,
      explanation: 'Obligations and cash live on the balance sheet. A beat is not that file.',
      conceptId: 'balance-sheet',
    },
    extraExercises: [
      {
        id: 'ex-fs-growth-recognize',
        kind: 'select',
        conceptId: 'revenue-growth',
        prompt: 'Harbor’s revenue is up 28%. What does that number, by itself, tell you?',
        choices: [
          'That Harbor is the automatic long',
          'Only that the top line grew — not whether growth is high-quality or a buy',
          'That margins and cash must also have improved',
          'That the next candle will follow revenue',
        ],
        correctIndex: 1,
        explanation: 'Growth is one evidence pile. Quality, cash, and price paid are separate questions — and none of them are an order.',
      },
      {
        id: 'ex-fs-earnings-recognize',
        kind: 'select',
        conceptId: 'earnings',
        prompt: 'Positive earnings while free cash flow is negative most honestly means…',
        choices: [
          'The business is proven high quality',
          'Earnings quality is in question until cash and leverage are read',
          'You should buy the dip',
          'Accounting profit always equals cash',
        ],
        correctIndex: 1,
        explanation: 'Profitability is earnings, margins, and cash conversion together — not a headline EPS beat.',
      },
      {
        id: 'ex-fs-leverage-guided',
        kind: 'scenario',
        guided: true,
        conceptId: 'balance-sheet',
        scenarioContext: 'concentrated_portfolio',
        situation: formatCompanyPair(CEDAR_RETAIL, HARBOR_COMPONENTS),
        prompt: 'Harbor’s debt/equity rose while Cedar’s stayed modest. Honest first read of the leverage file?',
        choices: [
          'Ignore Harbor’s debt because revenue grew',
          'Rising leverage is a balance-sheet risk question, not a short recommendation',
          'Buy Cedar automatically because debt is lower',
          'A tight 5-minute stop replaces the obligations file',
        ],
        correctIndex: 1,
        explanation: 'The balance sheet is where obligations live. This pair is educational sample data, not a pick list.',
        askEvidence: true,
      },
      {
        id: 'ex-fs-margins',
        kind: 'scenario',
        guided: true,
        conceptId: 'earnings',
        interactingConceptIds: ['revenue-growth'],
        scenarioContext: 'earnings',
        situation: formatCompanyCard(HARBOR_COMPONENTS),
        prompt: 'Harbor’s revenue is up and the operating margin is down. Honest interpretation?',
        choices: [
          'Automatic long — growth is what matters',
          'Growth is getting less efficient; read cash and leverage before treating earnings as quality',
          'Ignore Harbor forever because one year disappointed',
          'The chart already priced everything perfectly',
        ],
        correctIndex: 1,
        explanation: 'Rising revenue with falling margins is a quality question, not a buy signal.',
        askEvidence: true,
      },
      {
        id: 'ex-fs-compare',
        kind: 'compare',
        conceptId: 'revenue-growth',
        interactingConceptIds: ['business-quality', 'earnings', 'balance-sheet'],
        scenarioContext: 'ambiguous_setup',
        situation: formatCompanyPair(CEDAR_RETAIL, HARBOR_COMPONENTS),
        prompt: 'Which reading separates growth from quality?',
        leftLabel: 'Harbor is better because +28% revenue always wins',
        rightLabel: 'Harbor grew faster; Cedar’s margins and cash look more durable — neither is a buy instruction',
        correctIndex: 1,
        explanation:
          'Growth and quality can diverge. Naming that split is the skill. These names are educational samples.',
        askEvidence: true,
      },
      {
        id: 'ex-fs-balance',
        kind: 'scenario',
        conceptId: 'balance-sheet',
        scenarioContext: 'concentrated_portfolio',
        situation: formatCompanyCard(NORTHLINE_UTILITIES),
        prompt: 'Northline converts earnings to cash but must refinance a large debt stack. Honest risk note?',
        choices: [
          'Ignore debt — utilities never fail',
          'The balance sheet is the risk file: refinancing and leverage can dominate a pretty income line',
          'Buy more because cash conversion is high',
          'A tight stop on the 5-minute chart solves solvency',
        ],
        correctIndex: 1,
        explanation: 'Cash generation does not erase a refinancing window. This is not a recommendation.',
        askEvidence: true,
      },
      {
        id: 'ex-fs-mixed',
        kind: 'scenario',
        asTransfer: true,
        conceptId: 'earnings',
        interactingConceptIds: ['balance-sheet', 'revenue-growth'],
        scenarioContext: 'earnings',
        situation: `${formatCompanyCard(HARBOR_COMPONENTS)}\n\nLater you see the same pattern on a fictional software name with a different multiple.`,
        prompt: 'Earnings rose, free cash flow fell, and debt rose. The honest research note is…',
        choices: [
          'Automatic long — earnings are what matter',
          'Quality of earnings is in question; do not skip the cash and leverage file',
          'Ignore statements on that ticker forever',
          'The candle already priced everything perfectly',
        ],
        correctIndex: 1,
        explanation: 'Earnings without cash and with more leverage is a different business story — in any sector.',
        askEvidence: true,
      },
    ],
    quiz: [
      mcq(
        'q1',
        'A balance sheet is most useful for…',
        [
          'Tomorrow’s RSI',
          'Understanding obligations and buffers (cash, debt, assets)',
          'Guaranteeing a valuation',
          'Replacing a stop',
        ],
        1,
        [
          'Oscillators are price-derived.',
          'Solvency and leverage live here.',
          'Valuation is another lesson and still not a guarantee.',
          'Risk management still needs invalidation.',
        ],
        'balance-sheet',
      ),
      mcq(
        'q2',
        'Revenue up and operating margin down most honestly means…',
        [
          'Automatic long — growth is quality',
          'Growth is getting less efficient; cash and leverage still belong in the file',
          'Always short the name',
          'The next candle must follow the income statement',
        ],
        1,
        [
          'A faster top line is not the same as a better business.',
          'Efficiency and cash conversion are the quality questions.',
          'This academy does not recommend shorts either.',
          'Statements are lagged evidence, not a timing tool.',
        ],
        'revenue-growth',
      ),
      mcq(
        'q3',
        'An earnings beat with weaker cash conversion is…',
        [
          'A buy signal',
          'A quality-of-earnings question — still not an order',
          'Proof the multiple will expand',
          'A reason to turn stops off',
        ],
        1,
        [
          'A beat is not a recommendation.',
          'Profitability includes whether earnings became cash.',
          'Valuation is a separate comparison.',
          'Gap risk still needs a plan.',
        ],
        'earnings',
      ),
    ],
    takeaways: ['Know which statement answers which question.', 'A beat is not an order.', FUNDAMENTAL_SAMPLE_DISCLAIMER],
    practice: [
      {
        label: 'Changing-margins drill',
        href: '/practice?drill=changing-margins',
        description: 'Interpret efficiency, not a ticker tip.',
      },
      {
        label: 'Balance-sheet risk drill',
        href: '/practice?drill=balance-sheet-risk',
        description: 'Leverage as process context.',
      },
      {
        label: 'Historical earnings room',
        href: '/decision/replay-tv?episode=nvidia-earnings',
        description: 'Decide with information available then. Outcome is not the grade.',
      },
      JOURNAL,
    ],
    simulation: [
      {
        label: 'Earnings-window paper path',
        href: '/simulate?start=1&prep=earnings',
        description: 'Process only. Simulated P/L is not the grade.',
      },
    ],
    replay: [replayEpisodeLink('nvidia-earnings', 'Historical earnings room — then-available information only')],
    journalHref: '/journal?from=academy&notes=Statements%20vs%20thesis',
  }),

  makeFlagshipLesson({
    id: 'fund-valuation-quality',
    title: 'Valuation and advantage: paying for a business',
    description: 'Valuation asks what you pay. Competitive advantage asks why cash flows might last. Neither is a timing tool.',
    category: 'fundamental_analysis',
    difficulty: 'intermediate',
    durationMinutes: 12,
    sortOrder: 71,
    tags: ['valuation', 'pe', 'moat', 'advantage'],
    searchKeywords: ['valuation', 'p/e', 'competitive advantage', 'moat'],
    prerequisiteIds: ['fund-statements'],
    relatedLessonIds: ['fund-economy', 'dec-uncertainty'],
    conceptIds: ['valuation', 'competitive-position', 'business-quality'],
    objectives: [
      'Treat multiples as comparisons with context, not as buy alarms.',
      'Separate “good company” from “good price” and from “good time to size”.',
      'Name valuation uncertainty without turning a multiple into a recommendation.',
    ],
    whyItMatters:
      'Cheap can stay cheap. Wonderful businesses can be overpaid. Timing still needs a separate process.',
    explanation:
      'P/E and similar ratios need a peer and a growth/risk context. A moat is a reason cash might persist (switching costs, network, cost advantage) — still not proof.\n\nIf valuation is your thesis, invalidation might be “the multiple never mean-reverts and cash flows disappoint” — which can take longer than a swing stop. Say that honestly.',
    examples: [
      'Low P/E because the business is structurally impaired.',
      'High multiple because growth is real — still can draw down 40%.',
    ],
    mistakes: ['Buying solely because P/E is lower than last year.', 'Calling every brand a moat.'],
    limitations: ['This is literacy, not a DCF model.', FUNDAMENTAL_SAMPLE_DISCLAIMER],
    whenItWorks: [
      'You separate “good company”, “good price”, and “good time to size” — and refuse to treat a multiple as an order.',
    ],
    whenItFails: ['When the market is not paying attention to fundamentals this month. Then you need a different playbook or to stand aside.'],
    exercise: {
      id: 'ex-val-recognize',
      kind: 'select',
      conceptId: 'valuation',
      prompt: 'A richer P/E than peers most honestly means…',
      choices: [
        'Buy before the multiple mean-reverts',
        'You are paying more per unit of earnings — still not a timing or size instruction',
        'Skip risk management because the business is wonderful',
        'Short every rich multiple',
      ],
      correctIndex: 1,
      explanation: 'A multiple is a comparison under uncertainty. It is not a buy or sell alarm.',
    },
    extraExercises: [
      {
        id: 'ex-val-guided',
        kind: 'scenario',
        guided: true,
        conceptId: 'valuation',
        scenarioContext: 'ambiguous_setup',
        situation: formatCompanyCard(BRIGHTCANVAS),
        prompt: 'BrightCanvas grows faster and screens richer than Cedar. Honest first valuation note?',
        choices: [
          'The richer multiple is automatically a long',
          'Price paid is a separate question from growth and advantage — this file is not an order',
          'Ignore the multiple if the chart is trending',
          'Guarantee simulated profit because software compounds',
        ],
        correctIndex: 1,
        explanation: 'Wonderful businesses can be overpaid. Timing still needs its own process.',
        askEvidence: true,
      },
      {
        id: 'ex-val',
        kind: 'explain',
        conceptId: 'valuation',
        scenarioContext: 'ambiguous_setup',
        prompt: 'Why is “the P/E is low so I should buy” incomplete? (one or two sentences)',
        minChars: 24,
        modelAnswer:
          'A multiple needs context (growth, risk, peers) and still does not define timing, size, or invalidation. It is not a buy instruction.',
        explanation: 'Cheap is a comparison, not a thesis by itself.',
      },
      {
        id: 'ex-val-compare',
        kind: 'compare',
        conceptId: 'business-quality',
        interactingConceptIds: ['valuation', 'competitive-position'],
        scenarioContext: 'ambiguous_setup',
        situation: formatCompanyPair(CEDAR_RETAIL, BRIGHTCANVAS),
        prompt: 'Cedar is slower and cheaper-looking. BrightCanvas is faster and richer. Honest split?',
        leftLabel: 'Buy BrightCanvas — growth always deserves any multiple',
        rightLabel: 'Quality, price paid, and timing are three different questions — neither card is an order',
        correctIndex: 1,
        explanation: 'A wonderful business can be overpaid. A slower one can still be the wrong time to size.',
        askEvidence: true,
      },
      {
        id: 'ex-val-moat',
        kind: 'scenario',
        guided: true,
        conceptId: 'competitive-position',
        scenarioContext: 'ambiguous_setup',
        situation: formatCompanyCard(BRIGHTCANVAS),
        prompt: 'BrightCanvas claims switching costs. A free rival just launched. Honest advantage note?',
        choices: [
          'The moat is proven — size up',
          'Advantage is a claim under uncertainty; a free tier is a reason the claim might erode',
          'Ignore competition if the P/E is high',
          'Guarantee simulated profit because software compounds',
        ],
        correctIndex: 1,
        explanation: 'A moat is a research question, not a badge. This is not a sell recommendation either.',
        askEvidence: true,
      },
      {
        id: 'ex-val-transfer',
        kind: 'scenario',
        asTransfer: true,
        conceptId: 'valuation',
        interactingConceptIds: ['fundamental-uncertainty', 'competitive-position'],
        scenarioContext: 'event_window',
        situation: formatCompanyCard(BRIGHTCANVAS),
        prompt: 'Same BrightCanvas file, now two days before a fictional product event. Process?',
        choices: [
          'Full size — the multiple will mean-revert into the event',
          'Name that valuation uncertainty plus event gap risk still need size and invalidation — this is not a trade call',
          'Skip risk management because the moat is famous',
          'Treat the event as a guaranteed beat',
        ],
        correctIndex: 1,
        explanation: 'Unfamiliar calendar context does not turn a multiple into a signal.',
        askEvidence: true,
      },
    ],
    quiz: [
      mcq(
        'q1',
        'Competitive advantage most honestly helps you…',
        [
          'Time the next breakout',
          'Ask whether cash flows might persist — still with uncertainty',
          'Skip risk management',
          'Guarantee simulated profit',
        ],
        1,
        [
          'Moats are not oscillators.',
          'Persistence is a research question.',
          'You still need size and invalidation.',
          'Nothing guarantees paper or live profit.',
        ],
        'competitive-position',
      ),
      mcq(
        'q2',
        'A low multiple, by itself, is…',
        [
          'A buy instruction',
          'A comparison that still needs growth, risk, and peers — and still is not timing',
          'Proof the next candle is up',
          'A reason to skip invalidation',
        ],
        1,
        [
          'This academy does not turn multiples into orders.',
          'Cheap is a research question under uncertainty.',
          'Valuation is not a timing tool.',
          'Size and invalidation stay separate.',
        ],
        'valuation',
      ),
    ],
    takeaways: ['Price paid ≠ timing.', 'Advantage is a claim under uncertainty.', FUNDAMENTAL_SAMPLE_DISCLAIMER],
    journalHref: '/journal?from=academy&notes=Valuation%20vs%20timing',
    practice: [
      {
        label: 'Valuation uncertainty drill',
        href: '/practice?drill=valuation-uncertainty',
        description: 'Context for a multiple. Not a buy alarm.',
      },
      {
        label: 'Growth versus quality',
        href: '/practice?drill=growth-vs-quality',
        description: 'Unfamiliar pair. Transfer, not a pick.',
      },
      {
        label: 'Guidance-cut replay',
        href: '/decision/replay-tv?episode=guidance-cut-lab',
        description: 'Historical room. Outcome is one chapter.',
      },
      JOURNAL,
    ],
    simulation: [
      {
        label: 'Paper path — no correct trade',
        href: '/simulate?start=1&prep=earnings',
        description: 'Simulated P/L does not grade the decision.',
      },
    ],
    replay: [replayEpisodeLink('guidance-cut-lab', 'Guidance-cut room — a multiple is not a timing tool')],
  }),

  makeFlagshipLesson({
    id: 'fund-economy',
    title: 'Economic environment: the weather around the name',
    description: 'Rates, growth, inflation, and risk appetite change what “normal” looks like for many assets at once.',
    category: 'fundamental_analysis',
    difficulty: 'intermediate',
    durationMinutes: 11,
    sortOrder: 72,
    tags: ['economy', 'rates', 'macro'],
    searchKeywords: ['economic environment', 'interest rates', 'macro', 'inflation'],
    prerequisiteIds: ['fund-basics', 'fund-calendar'],
    relatedLessonIds: ['risk-correlation', 'dec-regime'],
    conceptIds: ['interest-rates', 'economic-releases', 'fundamental-uncertainty'],
    objectives: [
      'Name one macro driver that would hit several holdings together.',
      'Use the calendar as event risk, not as a crystal ball.',
    ],
    whyItMatters:
      'A perfect single-name chart can still live inside a rate shock. Portfolio process includes the weather.',
    explanation:
      'You do not need to forecast GDP. You need to know if your book is one-way on rates, USD, or growth.\n\nEvent risk: a print can gap through a swing stop. That belongs in size, not in surprise.',
    examples: [
      'Duration-sensitive growth names on a rate day.',
      'Cutting size into a known data release is process, not fear.',
    ],
    mistakes: ['Trading the headline instead of your playbook.', 'Ignoring that “unrelated” holdings share a macro factor.'],
    limitations: ['Macro narratives are often wrong. Use them as scenario risk, not as destiny.'],
    whenItFails: ['When you use macro to avoid ever taking a planned setup — that can be fear in a costume.'],
    exercise: {
      id: 'ex-eco',
      kind: 'choose',
      prompt: 'A major rate decision is tomorrow. Your swing stop is tight on a duration-sensitive name. Process?',
      choices: [
        'Full size — you have a MACD buy',
        'Acknowledge event risk: reduce size, widen only with less quantity, or stand aside',
        'Turn the stop off so you are not “shaken out”',
        'Delete the calendar',
      ],
      correctIndex: 1,
      explanation: 'Known event risk belongs in size. Removing the stop is not hedging — it is denial.',
      conceptId: 'interest-rates',
      askEvidence: true,
    },
    extraExercises: [
      {
        id: 'ex-eco-scenario',
        kind: 'scenario',
        asTransfer: true,
        conceptId: 'fundamental-uncertainty',
        interactingConceptIds: ['interest-rates', 'event-risk'],
        scenarioContext: 'event_window',
        prompt:
          'Inflation, rates, and a fictional earnings week land in the same window. Your book is duration-heavy. Honest process?',
        choices: [
          'Forecast the prints and size up',
          'Treat the cluster as shared-risk weather: cut size or stand aside unless you have a written playbook',
          'Assume the names are uncorrelated because they have different tickers',
          'This academy’s calendar is a buy list for the week',
        ],
        correctIndex: 1,
        explanation: 'Macro is scenario risk around the name, not a daily signal service.',
        askEvidence: true,
      },
    ],
    quiz: [
      mcq(
        'q1',
        'Macro is most useful as…',
        [
          'A daily buy/sell service',
          'A shared-risk scenario that can correlate the book',
          'A replacement for company analysis',
          'Proof candles do not matter',
        ],
        1,
        [
          'This academy is not a signal feed.',
          'Weather around the name.',
          'You still need the business file when that is the thesis.',
          'Price is still the object of execution.',
        ],
        'interest-rates',
      ),
    ],
    takeaways: ['Name the shared driver.', 'Event risk is a size input.'],
    practice: [
      {
        label: 'Rate-decision uncertainty',
        href: '/practice?drill=rate-decision-uncertainty',
        description: 'Two honest readings of the same print. Direction is not the grade.',
      },
      {
        label: 'FOMC replay room',
        href: '/decision/replay-tv?episode=fomc-decision-lab',
        description: 'Historical tape. Not a prediction of the next meeting.',
      },
      JOURNAL,
    ],
    simulation: [
      {
        label: 'Fictional rate-decision path',
        href: '/simulate?start=1&prep=rates',
        description: 'Uncertain paper event. Simulated P/L is context.',
      },
    ],
  }),

  makeFlagshipLesson({
    id: 'dec-thesis',
    title: 'Thesis and evidence: a claim you can kill',
    description: 'A thesis is a testable claim. Evidence is what supports or hurts it. If it cannot be killed, it is a vibe.',
    category: 'decision',
    difficulty: 'beginner',
    durationMinutes: 12,
    track: 'decision',
    sortOrder: 20,
    tags: ['thesis', 'evidence', 'assumptions'],
    searchKeywords: ['trading thesis', 'what is evidence', 'assumptions'],
    prerequisiteIds: ['dec-research-filter'],
    relatedLessonIds: ['dec-invalidation', 'dec-uncertainty', 'psych-confirmation'],
    conceptIds: ['thesis', 'evidence-quality'],
    objectives: [
      'Write a one-sentence claim plus the assumption underneath it.',
      'List evidence for and against before simulated size.',
    ],
    whyItMatters:
      'Without a thesis, review is just P/L theatre. Simulation asks for a thesis in the discipline challenge for this reason.',
    explanation:
      'Thesis: “Buyers still defend this zone while the higher-timeframe trend is up.” Assumption: “The zone still means demand.” Evidence: prior holds, participation. Against: failed hold, news, thin book.\n\nInvalidation is how the claim dies. Size is how much the death is allowed to cost.',
    examples: [
      'Paper ticket with thesis filled in — then close and compare outcome to the claim.',
      '“I like it” is not a thesis.',
    ],
    mistakes: ['Thesis after the fill.', 'Evidence that is only price going up.'],
    limitations: ['A good thesis can lose. That is uncertainty, not meaninglessness.'],
    whenItWorks: ['The claim is killable in one sentence, evidence for and against is listed, and size waits on that file.'],
    whenItFails: ['When you rewrite the thesis after the fact to match the outcome.'],
    exercise: {
      id: 'ex-th',
      kind: 'explain',
      prompt: 'Write a one-sentence simulated long thesis that includes what would prove it wrong.',
      minChars: 30,
      modelAnswer:
        'Example: Buyers defending the labelled support zone remains valid unless we accept below that zone on the daily — that is invalidation.',
      explanation: 'If you cannot name death, you cannot size.',
      conceptId: 'thesis',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'Evidence is…',
        [
          'Anything that agrees with you',
          'Observations that could support or hurt a testable claim',
          'Simulated profit',
          'A guaranteed scenario',
        ],
        1,
        [
          'That is confirmation bias.',
          'For and against.',
          'P/L is an outcome.',
          'Scenarios are later.',
        ],
        'evidence-quality',
      ),
    ],
    takeaways: ['Claims must be killable.', 'Assumptions should be named.'],
    practice: [
      JOURNAL,
      { label: 'Missing evidence drill', href: '/practice?drill=missing-evidence', description: 'A vibe is not a file.' },
      { label: 'Decision Lab', href: '/decision/lab', description: 'Write a full thesis before any simulated entry.' },
    ],
    simulation: [SIMULATE],
    replay: [replayEpisodeLink('nvidia-earnings', 'Write the claim with only then-available information')],
  }),

  makeFlagshipLesson({
    id: 'dec-uncertainty',
    title: 'Uncertainty, scenarios, and probabilities',
    description: 'You will not know. Scenarios and rough probabilities keep you honest. They are not a forecast product.',
    category: 'decision',
    difficulty: 'intermediate',
    durationMinutes: 12,
    track: 'decision',
    sortOrder: 21,
    tags: ['uncertainty', 'scenarios', 'probabilities'],
    searchKeywords: ['trading probabilities', 'scenarios', 'uncertainty'],
    prerequisiteIds: ['dec-thesis'],
    relatedLessonIds: ['dec-quality', 'risk-per-trade', 'fund-economy'],
    conceptIds: ['uncertainty', 'scenario-thinking'],
    objectives: [
      'List at least two scenarios besides your favourite.',
      'Use probabilities as humility, not as fake precision.',
    ],
    whyItMatters:
      'False certainty produces oversized bets. Saying “this is one plausible path” is how adults size.',
    explanation:
      'Base case, alternative, and invalidation path. Assigning 60/30/10 is a communication tool — it is not science to two decimals.\n\nIf all your probability sits on one path, you have not done the exercise.',
    examples: [
      'Break holds / fails back into range / gaps on news.',
      'Reducing size when two scenarios are both live.',
    ],
    mistakes: ['90% confidence on a chart with no file.', 'Refusing to trade ever because uncertainty exists — some uncertainty is the job. Size is the response.'],
    limitations: ['We are not running a Monte Carlo here. We are training language.'],
    whenItWorks: ['At least two live paths exist, size is smaller because of that, and invalidation is written for each.'],
    whenItFails: ['When “scenarios” are written after the outcome.'],
    exercise: {
      id: 'ex-unc',
      kind: 'rank',
      prompt: 'Rank from most honest to least, given an uncertain breakout.',
      items: [
        'Two scenarios + smaller size + clear invalidation',
        'One scenario stated as 95% with full size',
        'No scenario, market order because of FOMO',
      ],
      correctOrder: [0, 1, 2],
      explanation: 'Uncertainty → size. Fake precision is worse. No file is worst.',
      conceptId: 'uncertainty',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'A probability number in a journal is most useful as…',
        [
          'A guarantee',
          'A humility and sizing aid you can review later',
          'A live signal for others',
          'A way to skip invalidation',
        ],
        1,
        [
          'Numbers are not promises.',
          'Review: did you size as if you believed 60%, not 99%?',
          'This is not a social feed of signals.',
          'You still need a kill condition.',
        ],
        'uncertainty',
      ),
    ],
    takeaways: ['More than one path.', 'Precision theatre is not process.'],
    practice: [
      JOURNAL,
      {
        label: 'Rate-decision uncertainty drill',
        href: '/practice?drill=rate-decision-uncertainty',
        description: 'A known calendar event is not a forecast product.',
      },
    ],
    simulation: [SIMULATE],
    replay: [replayEpisodeLink('fomc-decision-lab', 'The meeting is known. The path is not.')],
  }),

  makeFlagshipLesson({
    id: 'dec-quality',
    title: 'Decision quality is not the P/L',
    description: 'A good decision can lose. A bad decision can win. Grade the file: evidence, size, invalidation, review.',
    category: 'decision',
    difficulty: 'beginner',
    durationMinutes: 10,
    track: 'decision',
    sortOrder: 22,
    tags: ['dqs', 'decision quality', 'process'],
    searchKeywords: ['decision quality', 'process not pnl', 'grade the decision'],
    prerequisiteIds: ['dec-thesis', 'dec-journaling'],
    relatedLessonIds: ['psych-discipline', 'risk-expectancy', 'dec-invalidation'],
    conceptIds: ['decision-quality'],
    objectives: [
      'Separate outcome from process in language.',
      'Use simulated results only as review input, never as the grade.',
    ],
    whyItMatters:
      'If you grade by paper profit, you will learn to chase. TradeAcademy’s DQS framing is process quality — never a prediction of price.',
    explanation:
      'After a close, ask: Was the thesis clear? Did size match uncertainty? Did I honour invalidation? What would I change?\n\nGreen can still be FOMO. Red can still be a correct scratch.',
    examples: [
      'Simulation close-review card asks those questions on purpose.',
      'A 2R winner with no thesis is not a skill story.',
    ],
    mistakes: ['“I was right” meaning “price went my way”.', 'Deleting history after a red patch.'],
    limitations: ['Process grades are still partly subjective. Use a stable checklist to reduce drift.'],
    whenItFails: ['When the checklist is only filled to look serious and never used at the ticket.'],
    exercise: {
      id: 'ex-dq',
      kind: 'compare',
      prompt: 'Which simulated close is higher process quality?',
      leftLabel: '+3R, no thesis, stop moved after entry for comfort',
      rightLabel: '−0.8R, written thesis, size 1%, stop honoured, journal completed',
      correctIndex: 1,
      explanation: 'Outcome is not the grade. The file is.',
      conceptId: 'decision-quality',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'In TradeAcademy, setup “confidence” / DQS is…',
        [
          'A forecast of direction',
          'A process-quality score, never a prediction of price',
          'A broker signal',
          'Simulated return annualised',
        ],
        1,
        [
          'We do not sell direction as certainty.',
          'Product rule: process, not prophecy.',
          'Not a broker.',
          'Return is not DQS.',
        ],
        'decision-quality',
      ),
    ],
    takeaways: ['Outcome ≠ quality.', 'Review the file every time.'],
    practice: [JOURNAL],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'port-diversification',
    title: 'Diversification: more than a longer watchlist',
    description: 'Diversification reduces the chance that one story owns your equity. It requires different drivers, not just different tickers.',
    category: 'portfolio',
    difficulty: 'beginner',
    durationMinutes: 11,
    sortOrder: 80,
    tags: ['diversification', 'allocation', 'correlation'],
    searchKeywords: ['diversification', 'how to diversify', 'portfolio'],
    prerequisiteIds: ['risk-exposure', 'risk-correlation'],
    relatedLessonIds: ['port-allocation', 'port-rebalancing', 'dec-portfolio-risk'],
    conceptIds: ['diversification'],
    objectives: [
      'Explain diversification as driver diversity.',
      'Use a single-name weight cap as a teaching constraint.',
    ],
    whyItMatters:
      'The paper diversification challenge (no name above 20% of equity) is a process rail. It is not a claim that 20% is magic in live markets.',
    explanation:
      'If one name is 40% of equity, you are not running a portfolio. You are running a single story with decorations.\n\nTrue diversification asks: different businesses, geographies, factors, and uncorrelated enough that they do not all gap together.',
    examples: [
      'Equity + a ballast idea versus five clones of the same factor.',
      'Simulation: reject a buy that would push a name through 20% in the challenge.',
    ],
    mistakes: ['20 tickers in one sector.', 'Diversifying only after a huge concentrated win — that is recency plus overconfidence.'],
    limitations: ['Diversification can reduce both pain and concentrated upside. That is the trade-off, not a bug.'],
    whenItFails: ['Crises when correlations spike.', 'When “diversified” names share one macro driver you did not name.'],
    exercise: {
      id: 'ex-divport',
      kind: 'calculate',
      prompt: 'Equity 100,000. Challenge cap 20% per name. Maximum market value for one simulated position?',
      expectedValue: 20000,
      tolerance: 1,
      unit: accountCurrencyHint(),
      explanation: '0.20 × 100,000 = 20,000. A teaching cap, not investment advice.',
      conceptId: 'diversification',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'Diversification fails as a costume when…',
        [
          'You hold cash',
          'Many tickers share one driver',
          'You journal',
          'You use paper trading',
        ],
        1,
        [
          'Cash is a valid allocation choice.',
          'Theme risk is the leak.',
          'Journaling helps you see it.',
          'Paper is how we practise the constraint.',
        ],
        'diversification',
      ),
    ],
    takeaways: ['Drivers, not ticker count.', 'Caps are process tools.'],
    practice: [PRACTICE],
    simulation: [SIMULATE],
  }),

  makeFlagshipLesson({
    id: 'port-allocation',
    title: 'Allocation and rebalancing: choosing weights on purpose',
    description: 'Allocation is the intended mix. Rebalancing is how you return to it when winners become the book.',
    category: 'portfolio',
    difficulty: 'intermediate',
    durationMinutes: 11,
    sortOrder: 81,
    tags: ['allocation', 'rebalancing', 'weights'],
    searchKeywords: ['allocation', 'rebalancing', 'portfolio weights'],
    prerequisiteIds: ['port-diversification'],
    relatedLessonIds: ['risk-drawdown', 'psych-overconfidence'],
    conceptIds: ['allocation', 'rebalancing'],
    objectives: [
      'State a target weight before drift happens.',
      'Treat trimming a winner as process, not as “calling a top”.',
    ],
    whyItMatters:
      'Without a target, every winner becomes destiny. Concentration then arrives as a surprise.',
    explanation:
      'Pick ranges, not fake precision (for example “this sleeve 10–20%”). When a name drifts above the range, reducing is restoring the plan — in simulation, it is still a decision to journal.\n\nRebalancing is not a prediction that the winner is finished.',
    examples: [
      'Target 15%, drifted to 28% after a run — trim toward the band, journal the reason.',
      'Never adding to a loser just to “get back to weight” without a thesis — that is a different error.',
    ],
    mistakes: ['Rebalancing every hour.', 'Refusing to trim because of taxes in a paper account that has no taxes — using that as an excuse.'],
    limitations: ['Live taxes and costs exist. This lesson is about intent, taught in paper.'],
    whenItFails: ['When the original allocation was never written.'],
    exercise: {
      id: 'ex-reb',
      kind: 'choose',
      prompt: 'A planned 15% sleeve is now 32% after a trend. Process-respecting move?',
      choices: [
        'Do nothing because winners should always run with no file',
        'Revisit the plan: either raise the band on purpose or trim toward the band and journal',
        'Add more so it becomes 50%',
        'Reset the whole simulation to hide the weight',
      ],
      correctIndex: 1,
      explanation: 'Drift is information. Respond with a written allocation decision, not autopilot or denial.',
      conceptId: 'rebalancing',
      askEvidence: true,
    },
    quiz: [
      mcq(
        'q1',
        'Rebalancing a winner toward a target weight is…',
        [
          'Always a prediction of a crash',
          'A way to keep the intended risk mix — still a decision under uncertainty',
          'Forbidden in paper trading',
          'The same as revenge trading',
        ],
        1,
        [
          'It can be wrong and still be process.',
          'Intentional weights.',
          'Paper is exactly where to practise it.',
          'Revenge is about losses and ego, not restoring a plan.',
        ],
        'rebalancing',
      ),
    ],
    takeaways: ['Weights need a target.', 'Trim can be process, not prophecy.'],
    practice: [JOURNAL],
    simulation: [SIMULATE],
  }),
];

function accountCurrencyHint(): string {
  return 'account currency';
}
