import type { LearningPath, TradingChecklist } from '../types/academy.types';

export const LEARNING_PATHS: LearningPath[] = [
  {
    id: 'path-decision-foundations',
    title: 'Decision Coach Foundations',
    description: 'Filter ideas, read regime, and protect your research time.',
    track: 'decision',
    icon: 'compass-outline',
    sortOrder: 1,
    isPremium: false,
    lessonIds: [
      'dec-research-filter',
      'dec-regime',
      'dec-setup-quality',
      'dec-invalidation',
      'dec-time-budget',
    ],
  },
  {
    id: 'path-self-review',
    title: 'Self-Review & Psychology',
    description: 'Journal, process grading, why-not discipline, and Trading DNA.',
    track: 'decision',
    icon: 'sparkles-outline',
    sortOrder: 2,
    isPremium: false,
    lessonIds: ['dec-journaling', 'dec-psychology', 'dec-why-not', 'dec-trading-dna', 'dec-portfolio-risk'],
  },
  {
    id: 'path-technical-foundations',
    title: 'Technical Foundations',
    description: 'Structure, candles, trend/range, volume, and multi-timeframe maps.',
    track: 'classic',
    icon: 'analytics-outline',
    sortOrder: 3,
    isPremium: false,
    lessonIds: ['ta-structure', 'ta-candles', 'ta-trend-range', 'ta-volume', 'ta-mtf'],
  },
  {
    id: 'path-risk-money',
    title: 'Risk & Money Management',
    description: 'Orders, sizing, expectancy, and a one-page trade plan.',
    track: 'classic',
    icon: 'shield-checkmark-outline',
    sortOrder: 4,
    isPremium: false,
    lessonIds: ['basics-rr', 'basics-orders', 'risk-position-sizing', 'risk-expectancy'],
  },
  {
    id: 'path-beyond-charts',
    title: 'Beyond the Chart',
    description: 'Catalysts, calendar risk, options expression, and crypto realities.',
    track: 'classic',
    icon: 'globe-outline',
    sortOrder: 5,
    isPremium: false,
    lessonIds: ['fund-basics', 'fund-calendar', 'opt-basics', 'crypto-structure'],
  },
];

export const DEFAULT_CHECKLISTS: TradingChecklist[] = [
  {
    id: 'pre-trade-checklist',
    title: 'Pre-Trade Checklist',
    description: 'Run before every live risk. Highlighted items adapt to regime when available.',
    isPremium: false,
    items: [
      {
        id: '1',
        text: 'Defined entry, invalidation, and management/targets',
        category: 'plan',
        sortOrder: 1,
        isRequired: true,
        hint: 'Invalidation is thesis failure — not a hopeful tight stop.',
      },
      {
        id: '2',
        text: 'Position size from $ risk and stop distance (≤ plan risk %)',
        category: 'risk',
        sortOrder: 2,
        isRequired: true,
      },
      {
        id: '3',
        text: 'Checked calendar for high-impact events on the hold horizon',
        category: 'fundamentals',
        sortOrder: 3,
        isRequired: true,
      },
      {
        id: '4',
        text: 'Regime and structure identified; setup fits the playbook',
        category: 'technical',
        sortOrder: 4,
        isRequired: true,
      },
      {
        id: '5',
        text: 'Emotional state is calm; no revenge or FOMO impulse',
        category: 'psychology',
        sortOrder: 5,
        isRequired: false,
      },
      {
        id: '6',
        text: 'Idea clears personal quality score / Radar priority',
        category: 'plan',
        sortOrder: 6,
        isRequired: true,
      },
      {
        id: '7',
        text: 'Correlated theme risk checked vs open positions',
        category: 'risk',
        sortOrder: 7,
        isRequired: true,
      },
    ],
  },
  {
    id: 'post-trade',
    title: 'Post-Trade Review',
    description: 'Close the learning loop while memory is fresh.',
    isPremium: false,
    items: [
      {
        id: 'p1',
        text: 'Logged thesis, invalidation, size rationale, and regime tag',
        category: 'journal',
        sortOrder: 1,
        isRequired: true,
      },
      {
        id: 'p2',
        text: 'Marked plan adherence: followed / bent / broke',
        category: 'journal',
        sortOrder: 2,
        isRequired: true,
      },
      {
        id: 'p3',
        text: 'Recorded planned R vs realized R',
        category: 'risk',
        sortOrder: 3,
        isRequired: true,
      },
      {
        id: 'p4',
        text: 'Noted emotion and any tilt protocol used',
        category: 'psychology',
        sortOrder: 4,
        isRequired: false,
      },
      {
        id: 'p5',
        text: 'One improvement sentence for next similar setup',
        category: 'review',
        sortOrder: 5,
        isRequired: true,
      },
    ],
  },
  {
    id: 'research-budget',
    title: 'Research Time Budget',
    description: 'Keep idea research from expanding into impulse.',
    isPremium: false,
    items: [
      {
        id: 'r1',
        text: 'Idea ranked in queue (not random tab surfing)',
        category: 'process',
        sortOrder: 1,
        isRequired: true,
      },
      {
        id: 'r2',
        text: 'Timer set (10–20 min) before deep work',
        category: 'process',
        sortOrder: 2,
        isRequired: true,
      },
      {
        id: 'r3',
        text: 'One-sentence thesis written before multi-TF diving',
        category: 'decision',
        sortOrder: 3,
        isRequired: true,
      },
      {
        id: 'r4',
        text: 'At timer end: candidate / watch / discard chosen',
        category: 'decision',
        sortOrder: 4,
        isRequired: true,
      },
      {
        id: 'r5',
        text: 'If discard: why-not reason noted',
        category: 'decision',
        sortOrder: 5,
        isRequired: false,
      },
    ],
  },
  {
    id: 'high-volatility',
    title: 'High-Volatility Day Protocol',
    description: 'Protect capital and attention when the tape is unstable.',
    isPremium: false,
    items: [
      {
        id: 'h1',
        text: 'Cut risk per trade (e.g. half normal R)',
        category: 'risk',
        sortOrder: 1,
        isRequired: true,
      },
      {
        id: 'h2',
        text: 'Only A+ setups; raise quality threshold',
        category: 'decision',
        sortOrder: 2,
        isRequired: true,
      },
      {
        id: 'h3',
        text: 'Widen respect for slippage; prefer exit certainty',
        category: 'execution',
        sortOrder: 3,
        isRequired: true,
      },
      {
        id: 'h4',
        text: 'No revenge adds; pause after any rule break',
        category: 'psychology',
        sortOrder: 4,
        isRequired: true,
      },
      {
        id: 'h5',
        text: 'Re-check calendar / headlines before new risk',
        category: 'fundamentals',
        sortOrder: 5,
        isRequired: true,
      },
    ],
  },
];
