import type { LearningPath, TradingChecklist } from '../types/academy.types';

/**
 * Foundations is the default journey (literacy first).
 * Decision Operator remains the process OS. Classic paths are first-class, not hidden.
 */
export interface AcademyPathMeta extends LearningPath {
  isDefault?: boolean;
  isSupporting?: boolean;
  unlockLabChallengeIds?: string[];
  iaHint?: string;
}

export const LEARNING_PATHS: AcademyPathMeta[] = [
  {
    id: 'path-foundations',
    title: 'Foundations',
    description:
      'What a market is, how orders match, and how to read a candle before any indicator.',
    track: 'classic',
    icon: 'school-outline',
    sortOrder: 0,
    isPremium: false,
    isDefault: true,
    iaHint: 'Start here — literacy before tactics',
    lessonIds: [
      'foundations-market',
      'foundations-asset-classes',
      'foundations-fx',
      'foundations-price',
      'basics-orders',
      'ta-candles',
      'foundations-timeframes',
      'ta-volume',
      'foundations-volatility',
      'foundations-liquidity',
    ],
  },
  {
    id: 'path-decision-operator',
    title: 'Decision Operator',
    description:
      'Filter attention → thesis & invalidation → regime → risk → psychology → Lab graduation.',
    track: 'decision',
    icon: 'navigate-circle-outline',
    sortOrder: 1,
    isPremium: false,
    iaHint: 'Decision-quality operating system',
    unlockLabChallengeIds: ['confirm-three', 'rr-two'],
    lessonIds: [
      'dec-research-filter',
      'dec-time-budget',
      'dec-setup-quality',
      'dec-thesis',
      'dec-invalidation',
      'dec-uncertainty',
      'dec-quality',
      'dec-regime',
      'dec-why-not',
      'dec-journaling',
      'dec-psychology',
      'dec-trading-dna',
      'dec-portfolio-risk',
    ],
  },
  {
    id: 'path-decision-foundations',
    title: 'Decision Coach Foundations',
    description: 'Filter ideas, read regime, and protect your research time.',
    track: 'decision',
    icon: 'compass-outline',
    sortOrder: 7,
    isPremium: false,
    isSupporting: true,
    iaHint: 'Shorter decision track if you want a focused pass',
    lessonIds: [
      'dec-research-filter',
      'dec-regime',
      'dec-setup-quality',
      'dec-invalidation',
      'dec-time-budget',
    ],
  },
  {
    id: 'path-self-review',
    title: 'Psychology',
    description: 'FOMO, revenge, loss aversion, bias, and discipline — from your notes, not from P&L.',
    track: 'decision',
    icon: 'sparkles-outline',
    sortOrder: 5,
    isPremium: false,
    unlockLabChallengeIds: ['stops-five'],
    lessonIds: [
      'dec-psychology',
      'psych-fomo',
      'psych-revenge',
      'psych-loss-aversion',
      'psych-confirmation',
      'psych-overconfidence',
      'psych-recency',
      'psych-discipline',
      'dec-journaling',
    ],
  },
  {
    id: 'path-technical-foundations',
    title: 'Technical Analysis',
    description: 'Structure, trend, S/R, momentum, MACD, volume, breakouts, and multi-timeframe maps.',
    track: 'classic',
    icon: 'analytics-outline',
    sortOrder: 3,
    isPremium: false,
    iaHint: 'Chart literacy after Foundations',
    unlockLabChallengeIds: ['trend-only'],
    lessonIds: [
      'ta-structure',
      'ta-candles',
      'ta-trend-range',
      'ta-moving-averages',
      'ta-rsi',
      'ta-macd',
      'ta-volume',
      'ta-false-breakouts',
      'ta-divergence',
      'ta-momentum',
      'ta-mtf',
    ],
  },
  {
    id: 'path-risk-money',
    title: 'Risk Management',
    description: 'Risk per trade, stops, sizing, drawdown, correlation, and risk of ruin — practised in paper, never as live advice.',
    track: 'classic',
    icon: 'shield-checkmark-outline',
    sortOrder: 4,
    isPremium: false,
    iaHint: 'Pairs with Practice sizing drills and simulation',
    unlockLabChallengeIds: ['rr-two', 'stops-five'],
    lessonIds: [
      'basics-rr',
      'risk-per-trade',
      'risk-stops',
      'risk-position-sizing',
      'risk-drawdown',
      'risk-exposure',
      'risk-correlation',
      'risk-ruin',
      'risk-expectancy',
    ],
  },
  {
    id: 'path-beyond-charts',
    title: 'Fundamental Research',
    description: 'Statements, valuation, advantage, and the economic environment — literacy, not a terminal.',
    track: 'classic',
    icon: 'globe-outline',
    sortOrder: 6,
    isPremium: false,
    iaHint: 'Optional depth — only if it changes a desk behavior',
    lessonIds: [
      'fund-basics',
      'fund-statements',
      'fund-valuation-quality',
      'fund-economy',
      'fund-calendar',
      'opt-basics',
      'crypto-structure',
    ],
  },
  {
    id: 'path-portfolio',
    title: 'Portfolio Management',
    description: 'Exposure, concentration, correlation, diversification, and rebalancing — practised with paper weights.',
    track: 'classic',
    icon: 'pie-chart-outline',
    sortOrder: 8,
    isPremium: false,
    iaHint: 'Pairs with the Simulate allocation view',
    lessonIds: [
      'risk-exposure',
      'risk-correlation',
      'port-diversification',
      'port-allocation',
      'dec-portfolio-risk',
    ],
  },
];

export const DEFAULT_CHECKLISTS: TradingChecklist[] = [
  {
    id: 'pre-trade-checklist',
    title: 'Pre-Trade Checklist',
    description: 'Run before every live risk. Highlighted items adapt to regime when available.',
    isPremium: false,
    items: [
      {
        id: '1',
        text: 'Defined entry, invalidation, and management/targets',
        category: 'plan',
        sortOrder: 1,
        isRequired: true,
        hint: 'Invalidation is thesis failure — not a hopeful tight stop.',
      },
      {
        id: '2',
        text: 'Position size from $ risk and stop distance (≤ plan risk %)',
        category: 'risk',
        sortOrder: 2,
        isRequired: true,
      },
      {
        id: '3',
        text: 'Checked calendar for high-impact events on the hold horizon',
        category: 'fundamentals',
        sortOrder: 3,
        isRequired: true,
      },
      {
        id: '4',
        text: 'Regime and structure identified; setup fits the playbook',
        category: 'technical',
        sortOrder: 4,
        isRequired: true,
      },
      {
        id: '5',
        text: 'Emotional state is calm; no revenge or FOMO impulse',
        category: 'psychology',
        sortOrder: 5,
        isRequired: false,
      },
      {
        id: '6',
        text: 'Idea clears personal quality score / Radar priority',
        category: 'plan',
        sortOrder: 6,
        isRequired: true,
      },
      {
        id: '7',
        text: 'Correlated theme risk checked vs open positions',
        category: 'risk',
        sortOrder: 7,
        isRequired: true,
      },
    ],
  },
  {
    id: 'post-trade',
    title: 'Post-Trade Review',
    description: 'Close the learning loop while memory is fresh.',
    isPremium: false,
    items: [
      {
        id: 'p1',
        text: 'Logged thesis, invalidation, size rationale, and regime tag',
        category: 'journal',
        sortOrder: 1,
        isRequired: true,
      },
      {
        id: 'p2',
        text: 'Marked plan adherence: followed / bent / broke',
        category: 'journal',
        sortOrder: 2,
        isRequired: true,
      },
      {
        id: 'p3',
        text: 'Recorded planned R vs realized R',
        category: 'risk',
        sortOrder: 3,
        isRequired: true,
      },
      {
        id: 'p4',
        text: 'Noted emotion and any tilt protocol used',
        category: 'psychology',
        sortOrder: 4,
        isRequired: false,
      },
      {
        id: 'p5',
        text: 'One improvement sentence for next similar setup',
        category: 'review',
        sortOrder: 5,
        isRequired: true,
      },
    ],
  },
  {
    id: 'research-budget',
    title: 'Research Time Budget',
    description: 'Keep idea research from expanding into impulse.',
    isPremium: false,
    items: [
      {
        id: 'r1',
        text: 'Idea ranked in queue (not random tab surfing)',
        category: 'process',
        sortOrder: 1,
        isRequired: true,
      },
      {
        id: 'r2',
        text: 'Timer set (10–20 min) before deep work',
        category: 'process',
        sortOrder: 2,
        isRequired: true,
      },
      {
        id: 'r3',
        text: 'One-sentence thesis written before multi-TF diving',
        category: 'decision',
        sortOrder: 3,
        isRequired: true,
      },
      {
        id: 'r4',
        text: 'At timer end: candidate / watch / discard chosen',
        category: 'decision',
        sortOrder: 4,
        isRequired: true,
      },
      {
        id: 'r5',
        text: 'If discard: why-not reason noted',
        category: 'decision',
        sortOrder: 5,
        isRequired: false,
      },
    ],
  },
  {
    id: 'high-volatility',
    title: 'High-Volatility Day Protocol',
    description: 'Protect capital and attention when the tape is unstable.',
    isPremium: false,
    items: [
      {
        id: 'h1',
        text: 'Cut risk per trade (e.g. half normal R)',
        category: 'risk',
        sortOrder: 1,
        isRequired: true,
      },
      {
        id: 'h2',
        text: 'Only A+ setups; raise quality threshold',
        category: 'decision',
        sortOrder: 2,
        isRequired: true,
      },
      {
        id: 'h3',
        text: 'Widen respect for slippage; prefer exit certainty',
        category: 'execution',
        sortOrder: 3,
        isRequired: true,
      },
      {
        id: 'h4',
        text: 'No revenge adds; pause after any rule break',
        category: 'psychology',
        sortOrder: 4,
        isRequired: true,
      },
      {
        id: 'h5',
        text: 'Re-check calendar / headlines before new risk',
        category: 'fundamentals',
        sortOrder: 5,
        isRequired: true,
      },
    ],
  },
];
