import type { SkillDomain } from '@/shared/constants/skill-domains';

import type { CompetencyConcept, CompetencyFamily } from '../types/competency.types';

function concept(
  id: string,
  title: string,
  family: CompetencyFamily,
  skillDomain: SkillDomain,
  relatedIds: string[],
  extras: Partial<Pick<CompetencyConcept, 'aliases' | 'secondaryFamilies' | 'description'>> = {},
): CompetencyConcept {
  return {
    id,
    title,
    family,
    skillDomain,
    relatedIds,
    aliases: extras.aliases ?? [],
    secondaryFamilies: extras.secondaryFamilies,
    description:
      extras.description ??
      `${title} is a process competency. Demonstration requires practice, not lesson completion.`,
  };
}

/**
 * Canonical competency registry.
 *
 * Existing learning-graph IDs are preserved where they already match
 * (`position-sizing`, `rsi`, `thesis`, …). New IDs extend the graph without
 * replacing Today’s Training or DQS.
 */
export const COMPETENCY_CONCEPTS: CompetencyConcept[] = [
  // --- Risk Management ---
  concept(
    'position-sizing',
    'Position sizing',
    'risk_management',
    'risk_management',
    ['risk-per-trade', 'invalidation', 'volatility-aware-risk', 'concentration-risk'],
    { description: 'Choosing size from risk, not from conviction or recent P/L.' },
  ),
  concept(
    'risk-per-trade',
    'Risk per trade',
    'risk_management',
    'risk_management',
    ['position-sizing', 'risk-reward', 'drawdown-management'],
    { description: 'Naming how much of the book is at risk before the fill.' },
  ),
  concept(
    'invalidation',
    'Invalidation',
    'thesis_decision_making',
    'decision_making',
    ['position-sizing', 'thesis', 'support', 'stop-logic'],
    {
      aliases: ['stops'],
      secondaryFamilies: ['risk_management'],
      description: 'Naming what would prove the idea wrong, then respecting that line.',
    },
  ),
  concept(
    'stop-logic',
    'Invalidation / stop logic',
    'risk_management',
    'risk_management',
    ['invalidation', 'risk-per-trade', 'volatility-aware-risk'],
    { description: 'Placing and honoring a process stop, not a hope-based exit.' },
  ),
  concept(
    'risk-reward',
    'Risk / reward',
    'risk_management',
    'risk_management',
    ['risk-per-trade', 'position-sizing'],
    { aliases: ['basics-rr'], description: 'Comparing downside defined in the plan to the upside case.' },
  ),
  concept(
    'drawdown-management',
    'Drawdown management',
    'risk_management',
    'risk_management',
    ['risk-per-trade', 'concentration-risk', 'discipline'],
    { aliases: ['drawdown'], description: 'Reducing size or pausing when the process, not the tape, is slipping.' },
  ),
  concept(
    'concentration-risk',
    'Concentration risk',
    'risk_management',
    'portfolio_management',
    ['position-sizing', 'diversification', 'drawdown-management'],
    { aliases: ['concentration'], description: 'Seeing when one name or theme dominates the book.' },
  ),
  concept(
    'volatility-aware-risk',
    'Volatility-aware risk',
    'risk_management',
    'risk_management',
    ['position-sizing', 'event-volatility', 'stop-logic'],
    { aliases: ['volatility'], description: 'Sizing and invalidation that respect current volatility, not a fixed habit.' },
  ),
  concept(
    'diversification',
    'Diversification',
    'risk_management',
    'portfolio_management',
    ['concentration-risk', 'position-sizing', 'event-risk'],
    { description: 'Spreading process risk across uncorrelated ideas — not collecting tickers.' },
  ),

  // --- Technical Analysis ---
  concept(
    'chart-interpretation',
    'Chart structure',
    'technical_analysis',
    'chart_reading',
    ['trend-identification', 'support', 'volume', 'multi-timeframe'],
    {
      aliases: ['chart-structure'],
      description: 'Reading structure (trend, range, swing) before applying a tool.',
    },
  ),
  concept(
    'trend-identification',
    'Trend identification',
    'technical_analysis',
    'chart_reading',
    ['chart-interpretation', 'momentum', 'moving-averages'],
    { description: 'Saying whether price is trending, ranging, or transitioning — and why.' },
  ),
  concept(
    'support',
    'Support and resistance',
    'technical_analysis',
    'chart_reading',
    ['chart-interpretation', 'breakouts', 'false-breakouts', 'invalidation'],
    { aliases: ['find-support'], description: 'Locating levels that mattered before, and treating them as hypotheses.' },
  ),
  concept(
    'breakouts',
    'Breakouts',
    'technical_analysis',
    'technical_analysis',
    ['support', 'false-breakouts', 'volume', 'momentum'],
    { description: 'Judging whether a level break has evidence, not just a print beyond the line.' },
  ),
  concept(
    'false-breakouts',
    'False breakouts',
    'technical_analysis',
    'technical_analysis',
    ['breakouts', 'support', 'false-signals', 'invalidation'],
    { description: 'Recognizing failed breaks and the process response (stand down, not chase).' },
  ),
  concept(
    'momentum',
    'Momentum',
    'technical_analysis',
    'technical_analysis',
    ['rsi', 'trend-identification', 'divergence', 'volume'],
    { description: 'Reading whether participation is expanding or fading with the move.' },
  ),
  concept(
    'volume',
    'Volume',
    'technical_analysis',
    'chart_reading',
    ['breakouts', 'momentum', 'chart-interpretation'],
    { description: 'Using volume as context for conviction in a move, not as a signal.' },
  ),
  concept(
    'moving-averages',
    'Moving averages',
    'technical_analysis',
    'technical_analysis',
    ['trend-identification', 'momentum', 'multi-timeframe'],
    { aliases: ['macd'], description: 'Using averages as structure context, not as automatic entries.' },
  ),
  concept(
    'rsi',
    'RSI / momentum interpretation',
    'technical_analysis',
    'technical_analysis',
    ['momentum', 'divergence', 'false-signals'],
    { description: 'Interpreting RSI as momentum context, not as a buy/sell trigger.' },
  ),
  concept(
    'divergence',
    'Divergence',
    'technical_analysis',
    'technical_analysis',
    ['rsi', 'momentum', 'false-signals'],
    { description: 'Noticing disagreement between price and momentum — and the uncertainty that creates.' },
  ),
  concept(
    'multi-timeframe',
    'Multi-timeframe interpretation',
    'technical_analysis',
    'technical_analysis',
    ['chart-interpretation', 'trend-identification', 'moving-averages'],
    { aliases: ['timeframes'], description: 'Checking that the working timeframe is not fighting a larger structure.' },
  ),
  concept(
    'false-signals',
    'False signals',
    'technical_analysis',
    'technical_analysis',
    ['divergence', 'false-breakouts', 'rsi'],
    { description: 'Treating indicator prints as fallible evidence, not instructions.' },
  ),
  concept(
    'liquidity',
    'Liquidity',
    'technical_analysis',
    'market_understanding',
    ['support', 'volume', 'volatility-aware-risk'],
    { description: 'Noticing when a market is thin enough that process risk changes.' },
  ),

  // --- Fundamental Research ---
  concept(
    'revenue-growth',
    'Revenue growth',
    'fundamental_research',
    'fundamental_analysis',
    ['earnings', 'business-quality', 'fundamental-uncertainty'],
    { description: 'Reading growth as evidence with limits, not as a forecast.' },
  ),
  concept(
    'earnings',
    'Earnings',
    'fundamental_research',
    'fundamental_analysis',
    ['revenue-growth', 'valuation', 'earnings-events', 'thesis'],
    { description: 'Using earnings as one evidence pile — quality, not a directional tip.' },
  ),
  concept(
    'valuation',
    'Valuation',
    'fundamental_research',
    'fundamental_analysis',
    ['earnings', 'business-quality', 'fundamental-uncertainty'],
    { description: 'Comparing price to a stated framework, and naming what the framework misses.' },
  ),
  concept(
    'balance-sheet',
    'Balance sheet',
    'fundamental_research',
    'fundamental_analysis',
    ['business-quality', 'fundamental-uncertainty'],
    { description: 'Reading leverage, cash, and obligations as risk context.' },
  ),
  concept(
    'competitive-position',
    'Competitive position',
    'fundamental_research',
    'fundamental_analysis',
    ['business-quality', 'revenue-growth'],
    { aliases: ['moat'], description: 'Describing why a business might keep earning — and what would erode that.' },
  ),
  concept(
    'business-quality',
    'Business quality',
    'fundamental_research',
    'fundamental_analysis',
    ['competitive-position', 'revenue-growth', 'balance-sheet'],
    { description: 'Separating a good business from a good process decision at this price.' },
  ),
  concept(
    'fundamental-uncertainty',
    'Fundamental uncertainty',
    'fundamental_research',
    'fundamental_analysis',
    ['uncertainty', 'valuation', 'earnings'],
    { description: 'Saying what the filings and estimates cannot tell you.' },
  ),

  // --- Psychology ---
  concept(
    'fomo',
    'FOMO',
    'psychology',
    'psychology',
    ['emotional-decision-making', 'revenge-trading', 'overconfidence'],
    { description: 'Noticing the urge to enter because others already did.' },
  ),
  concept(
    'confirmation-bias',
    'Confirmation bias',
    'psychology',
    'psychology',
    ['thesis', 'evidence-quality', 'alternative-explanations'],
    {
      description: 'Catching the habit of collecting only agreeing evidence.',
    },
  ),
  concept(
    'overconfidence',
    'Overconfidence',
    'psychology',
    'psychology',
    ['confirmation-bias', 'position-sizing', 'uncertainty'],
    { description: 'Calibrating confidence to evidence, not to a recent win.' },
  ),
  concept(
    'loss-aversion',
    'Loss aversion',
    'psychology',
    'psychology',
    ['invalidation', 'discipline', 'drawdown-management'],
    { description: 'Noticing when holding is about avoiding a recorded loss, not the thesis.' },
  ),
  concept(
    'revenge-trading',
    'Revenge trading',
    'psychology',
    'psychology',
    ['fomo', 'emotional-decision-making', 'discipline'],
    { aliases: ['revenge'], description: 'Recognizing the urge to “get it back” after a loss.' },
  ),
  concept(
    'recency-bias',
    'Recency bias',
    'psychology',
    'psychology',
    ['overconfidence', 'avoiding-hindsight', 'event-risk'],
    { description: 'Weighting the last print or headline more than the written process.' },
  ),
  concept(
    'anchoring',
    'Anchoring',
    'psychology',
    'psychology',
    ['valuation', 'recency-bias', 'thesis'],
    { description: 'Noticing when an old price or target is doing the deciding.' },
  ),
  concept(
    'discipline',
    'Discipline',
    'psychology',
    'psychology',
    ['following-a-plan', 'emotional-decision-making', 'drawdown-management'],
    { secondaryFamilies: ['review_process'], description: 'Doing the next process step you already wrote down.' },
  ),
  concept(
    'emotional-decision-making',
    'Emotional decision-making',
    'psychology',
    'psychology',
    ['fomo', 'revenge-trading', 'discipline'],
    { description: 'Separating a feeling from a written reason to act or stand down.' },
  ),

  // --- Thesis and Decision-Making ---
  concept(
    'thesis',
    'Thesis construction',
    'thesis_decision_making',
    'decision_making',
    ['evidence-quality', 'invalidation', 'uncertainty', 'alternative-explanations'],
    { description: 'Writing a testable idea before size, not a slogan after the fill.' },
  ),
  concept(
    'evidence-quality',
    'Evidence quality',
    'thesis_decision_making',
    'decision_making',
    ['thesis', 'alternative-explanations', 'confirmation-bias'],
    { aliases: ['evidence'], description: 'Judging whether the pile of evidence is independent and sufficient.' },
  ),
  concept(
    'alternative-explanations',
    'Alternative explanations',
    'thesis_decision_making',
    'decision_making',
    ['thesis', 'evidence-quality', 'confirmation-bias', 'uncertainty'],
    { description: 'Naming at least one other story that fits the same facts.' },
  ),
  concept(
    'uncertainty',
    'Uncertainty recognition',
    'thesis_decision_making',
    'decision_making',
    ['thesis', 'event-risk', 'fundamental-uncertainty', 'scenario-thinking'],
    { description: 'Saying what is unknown and sizing (or skipping) accordingly.' },
  ),
  concept(
    'scenario-thinking',
    'Scenario thinking',
    'thesis_decision_making',
    'decision_making',
    ['uncertainty', 'invalidation', 'adapting-decisions'],
    { description: 'Holding more than one path and a response for each.' },
  ),
  concept(
    'decision-consistency',
    'Decision consistency',
    'thesis_decision_making',
    'decision_making',
    ['thesis', 'following-a-plan', 'discipline'],
    { description: 'Applying the same process rules across similar cases.' },
  ),
  concept(
    'avoiding-hindsight',
    'Avoiding hindsight',
    'thesis_decision_making',
    'decision_making',
    ['post-decision-review', 'recency-bias', 'extracting-lessons'],
    { description: 'Reviewing the decision with the information you had then, not the print now.' },
  ),

  // --- Event Risk ---
  concept(
    'event-risk',
    'Event risk',
    'event_risk',
    'fundamental_analysis',
    ['uncertainty', 'information-timing', 'event-volatility', 'earnings-events'],
    { description: 'Treating scheduled and unscheduled events as process risk, not as tips.' },
  ),
  concept(
    'economic-releases',
    'Economic releases',
    'event_risk',
    'fundamental_analysis',
    ['event-risk', 'inflation', 'employment', 'information-timing'],
    { description: 'Preparing a process for data prints instead of reacting to the headline.' },
  ),
  concept(
    'inflation',
    'Inflation / CPI',
    'event_risk',
    'fundamental_analysis',
    ['economic-releases', 'central-bank', 'event-volatility'],
    { description: 'Studying inflation prints as context for uncertainty, not as a trade call.' },
  ),
  concept(
    'employment',
    'Employment data',
    'event_risk',
    'fundamental_analysis',
    ['economic-releases', 'event-risk', 'central-bank'],
    { description: 'Reading labor data as one input among several, with timing risk.' },
  ),
  concept(
    'central-bank',
    'Central bank decisions',
    'event_risk',
    'fundamental_analysis',
    ['interest-rates', 'event-risk', 'uncertainty', 'information-timing'],
    { description: 'Preparing for policy decisions: scenarios, not predicted moves.' },
  ),
  concept(
    'interest-rates',
    'Interest rates',
    'event_risk',
    'fundamental_analysis',
    ['central-bank', 'event-risk', 'uncertainty'],
    { description: 'Using rate context as a regime input, never as a signal.' },
  ),
  concept(
    'earnings-events',
    'Earnings events',
    'event_risk',
    'fundamental_analysis',
    ['earnings', 'event-risk', 'event-volatility', 'information-timing'],
    { description: 'Separating the research pile from the timing risk of the print.' },
  ),
  concept(
    'geopolitical',
    'Geopolitical events',
    'event_risk',
    'fundamental_analysis',
    ['event-risk', 'commodity-shocks', 'uncertainty'],
    { description: 'Recognizing when the information set is incomplete and unstable.' },
  ),
  concept(
    'commodity-shocks',
    'Commodity shocks',
    'event_risk',
    'fundamental_analysis',
    ['geopolitical', 'event-volatility', 'event-risk'],
    { description: 'Seeing supply shocks as regime changes, not as automatic continuations.' },
  ),
  concept(
    'event-volatility',
    'Volatility around events',
    'event_risk',
    'risk_management',
    ['volatility-aware-risk', 'event-risk', 'position-sizing'],
    { secondaryFamilies: ['risk_management'], description: 'Adjusting process (size, stand-down) when event vol expands.' },
  ),
  concept(
    'information-timing',
    'Information timing',
    'event_risk',
    'decision_making',
    ['event-risk', 'uncertainty', 'avoiding-hindsight'],
    { description: 'Knowing what you knew when you decided — and what arrived later.' },
  ),

  // --- Review and Process ---
  concept(
    'journaling',
    'Journaling',
    'review_process',
    'process_discipline',
    ['post-decision-review', 'extracting-lessons', 'identifying-mistakes'],
    { description: 'Recording the process (thesis, invalidation, emotion flags) without needing a novel.' },
  ),
  concept(
    'post-decision-review',
    'Post-decision review',
    'review_process',
    'process_discipline',
    ['journaling', 'avoiding-hindsight', 'identifying-strengths', 'identifying-mistakes'],
    { description: 'Comparing the plan you wrote to the actions you took.' },
  ),
  concept(
    'identifying-mistakes',
    'Identifying mistakes',
    'review_process',
    'process_discipline',
    ['post-decision-review', 'extracting-lessons', 'adapting-decisions'],
    { description: 'Naming process errors without rewriting them as “the market was wrong”.' },
  ),
  concept(
    'identifying-strengths',
    'Identifying strengths',
    'review_process',
    'process_discipline',
    ['post-decision-review', 'extracting-lessons', 'decision-consistency'],
    { description: 'Keeping the process steps that already worked, so review is not only deficit-focused.' },
  ),
  concept(
    'following-a-plan',
    'Following a plan',
    'review_process',
    'process_discipline',
    ['discipline', 'decision-consistency', 'journaling'],
    { description: 'Acting from a written plan, or standing down when there is none.' },
  ),
  concept(
    'extracting-lessons',
    'Extracting lessons',
    'review_process',
    'process_discipline',
    ['identifying-mistakes', 'identifying-strengths', 'adapting-decisions'],
    { description: 'Turning one review into a specific next-time rule.' },
  ),
  concept(
    'adapting-decisions',
    'Adapting future decisions',
    'review_process',
    'process_discipline',
    ['extracting-lessons', 'scenario-thinking', 'decision-consistency'],
    { description: 'Changing the next process step because the last review earned it.' },
  ),

  // --- Existing graph extras ---
  concept(
    'fx',
    'Currency pairs',
    'event_risk',
    'market_understanding',
    ['event-risk', 'interest-rates'],
    { aliases: ['currency-pairs'], description: 'Studying FX as a quoted pair with event and rate context.' },
  ),
];

/** Product-required concept coverage. Used by taxonomy validation tests. */
export const REQUIRED_CONCEPT_GROUPS: Record<CompetencyFamily, readonly string[]> = {
  risk_management: [
    'position-sizing',
    'risk-per-trade',
    'invalidation',
    'stop-logic',
    'risk-reward',
    'drawdown-management',
    'concentration-risk',
    'volatility-aware-risk',
  ],
  technical_analysis: [
    'chart-interpretation',
    'trend-identification',
    'support',
    'breakouts',
    'false-breakouts',
    'momentum',
    'volume',
    'moving-averages',
    'rsi',
    'divergence',
    'multi-timeframe',
  ],
  fundamental_research: [
    'revenue-growth',
    'earnings',
    'valuation',
    'balance-sheet',
    'competitive-position',
    'business-quality',
    'fundamental-uncertainty',
  ],
  psychology: [
    'fomo',
    'confirmation-bias',
    'overconfidence',
    'loss-aversion',
    'revenge-trading',
    'recency-bias',
    'anchoring',
    'discipline',
    'emotional-decision-making',
  ],
  thesis_decision_making: [
    'thesis',
    'evidence-quality',
    'alternative-explanations',
    'uncertainty',
    'invalidation',
    'scenario-thinking',
    'decision-consistency',
    'avoiding-hindsight',
  ],
  event_risk: [
    'event-risk',
    'economic-releases',
    'inflation',
    'employment',
    'central-bank',
    'earnings-events',
    'geopolitical',
    'commodity-shocks',
    'event-volatility',
    'information-timing',
  ],
  review_process: [
    'journaling',
    'post-decision-review',
    'identifying-mistakes',
    'identifying-strengths',
    'following-a-plan',
    'extracting-lessons',
    'adapting-decisions',
  ],
};

export const COMPETENCY_FAMILIES = Object.keys(REQUIRED_CONCEPT_GROUPS) as CompetencyFamily[];

export const FORBIDDEN_MASTERY_TERMS = [
  'certified',
  'qualified',
  'live-ready',
  'professionally ready',
  'ready for live',
  'ready for real-money',
  'ready to trade',
  'professional',
  'guaranteed',
  'expert',
] as const;
