import type {
  ReplayTvCollection,
  ReplayTvEpisode,
  ReplayTvNewsItem,
} from '@/features/decision-replay-tv/types/replay-tv.types';

export const REPLAY_TV_COLLECTIONS: ReplayTvCollection[] = [
  {
    id: 'featured',
    title: 'Featured',
    description: 'Start here — spoiler-safe historical decision rooms.',
  },
  {
    id: 'crashes',
    title: 'Market Crashes',
    description: 'Stress regimes where attention and invalidation matter most.',
  },
  {
    id: 'manias',
    title: 'Bubbles & Crowds',
    description: 'Crowded narratives, squeezes, and attention traps.',
  },
  {
    id: 'policy',
    title: 'Macro Events',
    description: 'Macro and political surprises that reprice risk.',
  },
  {
    id: 'earnings',
    title: 'Earnings',
    description: 'Single-name narrative pivots without hindsight.',
  },
  {
    id: 'crypto',
    title: 'Crypto Stress',
    description: 'Trust and liquidity shocks in digital markets.',
  },
  {
    id: 'regime_changes',
    title: 'Regime Changes',
    description: 'When the market’s operating system flips.',
  },
  {
    id: 'false_breakouts',
    title: 'False Breakouts',
    description: 'Structure that invites chase — process that refuses it.',
  },
  {
    id: 'psychology',
    title: 'Psychology',
    description: 'FOMO, fear, and attention under uncertainty.',
  },
  {
    id: 'risk_management',
    title: 'Risk Management',
    description: 'Downside framing before depth of research.',
  },
  {
    id: 'uncertainty',
    title: 'Uncertainty',
    description: 'Ambiguous tapes where skipping is a first-class decision.',
  },
];

const educationalNote =
  'Educational reconstruction for decision practice. Bars are sample/approximate — not exchange ticks. Outcomes are spoiler-gated until reveal.';

function news(
  id: string,
  availableAtIndex: number,
  headline: string,
  detail: string,
): ReplayTvNewsItem {
  return { id, availableAtIndex, headline, detail };
}

function academyLinks(lessonIds: string[]) {
  return lessonIds.map((lessonId) => ({
    kind: 'academy' as const,
    label: 'Related Academy lesson',
    href: `/academy/lesson/${lessonId}`,
  }));
}

export const REPLAY_TV_EPISODES: ReplayTvEpisode[] = [
  {
    id: 'covid-crash',
    title: '2020 — The COVID Crash',
    subtitle: 'When risk assets reprice overnight',
    teaser: 'A calm trend meets an accelerating fear regime. Future path hidden.',
    historicalOutcome:
      'Historically, early 2020 saw a violent liquidity-driven drawdown followed by an extraordinary policy response and recovery. The lesson is process under stress — not a forecast template.',
    collectionIds: ['featured', 'crashes', 'regime_changes', 'psychology'],
    symbol: 'SPX',
    symbolLabel: 'Broad equity index (proxy)',
    interval: '1d',
    difficulty: 'intermediate',
    skills: ['regime', 'invalidation', 'time_budget'],
    eraLabel: '2020',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Macro headlines are escalating; volatility is waking up.',
      'Your job is research allocation — not predicting the bottom.',
      'Name what would make you stop watching this tape.',
    ],
    availableNews: [
      news('n1', 20, 'Virus headlines accelerate', 'Travel and demand uncertainty rises in the story.'),
      news('n2', 35, 'Volatility wakes up', 'Risk assets begin to reprice; liquidity questions appear.'),
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 28,
        prompt: 'Volatility is rising. What would you do with your research attention?',
        mentorFollowUp:
          'What invalidation would force you to step away — a level, a time budget, or a regime change?',
        teachingNote: 'Stress regimes punish overconfidence. Protecting attention is a valid decision.',
        availableDataNotes: ['Daily tape through freeze', 'Macro headlines available up to this bar'],
        newsIdsVisible: ['n1'],
        hypothesisPrompt: 'What is your working regime hypothesis?',
      },
      {
        id: 'c2',
        freezeIndex: 42,
        prompt: 'The move has accelerated. Reassess: research more, wait, or protect attention?',
        mentorFollowUp: 'Are you updating your thesis — or chasing the narrative because others are?',
        teachingNote: 'Blind replay trains process under uncertainty. Outcome knowledge comes later.',
        availableDataNotes: ['Additional stress headlines now visible'],
        newsIdsVisible: ['n1', 'n2'],
      },
    ],
    pathSeed: 202003,
    pathShape: 'crash',
    barCount: 60,
    academyLessonIds: ['dec-regime', 'dec-invalidation'],
    durationMinutes: 20,
    estimatedDecisionCount: 2,
    markets: ['stocks', 'macro'],
    tradingStyles: ['swing', 'day', 'any'],
    scoringEmphasis: ['patience', 'risk', 'invalidation', 'process'],
    educationalLinks: academyLinks(['dec-regime', 'dec-invalidation']),
  },
  {
    id: 'gamestop-squeeze',
    title: '2021 — GameStop',
    subtitle: 'Crowds, short interest, and attention',
    teaser: 'A beaten-down name starts attracting unusual attention. Path hidden.',
    historicalOutcome:
      'The GameStop episode became a textbook attention/squeeze narrative. Educational focus: process under crowd pressure — never a playbook to copy.',
    collectionIds: ['featured', 'manias', 'psychology', 'uncertainty'],
    symbol: 'GME',
    symbolLabel: 'Single-name equity (proxy)',
    interval: '1d',
    difficulty: 'advanced',
    skills: ['attention', 'crowd', 'thesis_quality'],
    eraLabel: '2021',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Social chatter and short interest dominate the story.',
      'Liquidity can disappear when everyone wants the same door.',
      'Decide how much research time this deserves — not a price target.',
    ],
    availableNews: [
      news('n1', 22, 'Retail attention spikes', 'Social volume around the name rises sharply.'),
      news('n2', 40, 'Short interest dominates the narrative', 'Crowd and positioning stories intensify.'),
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 30,
        prompt: 'Attention is spiking. Is this worth a thesis — or a skip?',
        mentorFollowUp: 'What would make this a research trap rather than a research priority?',
        teachingNote: 'Crowd episodes often reward waiting for a clear research question.',
        newsIdsVisible: ['n1'],
        choices: ['research_more', 'write_thesis', 'wait', 'skip', 'protect_attention'],
      },
      {
        id: 'c2',
        freezeIndex: 48,
        prompt: 'Price action is violent. Protect attention or write a structured thesis?',
        mentorFollowUp: 'Can you name an invalidation that is not “it stopped going up”?',
        teachingNote: 'Process quality beats narrative excitement.',
        newsIdsVisible: ['n1', 'n2'],
      },
    ],
    pathSeed: 202101,
    pathShape: 'squeeze',
    barCount: 64,
    academyLessonIds: ['dec-time-budget', 'dec-setup-quality'],
    durationMinutes: 25,
    estimatedDecisionCount: 2,
    markets: ['stocks'],
    tradingStyles: ['day', 'swing', 'any'],
    scoringEmphasis: ['evidence', 'alternatives', 'patience', 'process'],
    educationalLinks: academyLinks(['dec-time-budget', 'dec-setup-quality']),
    premiumOnly: true,
  },
  {
    id: 'lehman-weekend',
    title: '2008 — The Financial Crisis',
    subtitle: 'Systemic risk and research triage',
    teaser: 'Credit stress headlines intensify. You cannot see what comes next.',
    historicalOutcome:
      'The Lehman Brothers collapse marked a systemic phase of the Global Financial Crisis. Replay trains triage and invalidation — not crisis trading.',
    collectionIds: ['featured', 'crashes', 'risk_management', 'regime_changes'],
    symbol: 'SPX',
    symbolLabel: 'Broad equity index (proxy)',
    interval: '1d',
    difficulty: 'expert',
    skills: ['regime', 'risk', 'patience'],
    eraLabel: '2008',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Financial plumbing stress is the story — not a single ticker.',
      'Your edge here is deciding what to study, not predicting the weekend.',
      'Write what would prove your working view wrong.',
    ],
    availableNews: [
      news('n1', 24, 'Credit stress deepens', 'Interbank trust and funding narratives worsen.'),
      news('n2', 38, 'Weekend risk talk rises', 'Systemic headlines dominate research desks.'),
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 32,
        prompt: 'Credit headlines worsen. How do you allocate research time?',
        mentorFollowUp: 'Is your plan process-driven, or are you reacting to fear?',
        teachingNote: 'Systemic regimes demand smaller research bets and clearer stops.',
        newsIdsVisible: ['n1'],
      },
      {
        id: 'c2',
        freezeIndex: 44,
        prompt: 'Stress accelerates. Reassess attention vs deep research.',
        mentorFollowUp: 'What is the downside if your assumption about “containment” is wrong?',
        teachingNote: 'Expert rooms reward downside framing before depth.',
        newsIdsVisible: ['n1', 'n2'],
      },
    ],
    pathSeed: 200809,
    pathShape: 'slow_bleed',
    barCount: 55,
    academyLessonIds: ['dec-regime', 'dec-portfolio-risk'],
    durationMinutes: 30,
    estimatedDecisionCount: 2,
    markets: ['stocks', 'macro'],
    tradingStyles: ['swing', 'position', 'any'],
    scoringEmphasis: ['risk', 'invalidation', 'patience', 'process'],
    educationalLinks: academyLinks(['dec-regime', 'dec-portfolio-risk']),
    premiumOnly: true,
  },
  {
    id: 'black-monday',
    title: 'Black Monday Shock',
    subtitle: 'Gap risk and decision quality',
    teaser: 'A calm stretch ends. The next bars are hidden on purpose.',
    historicalOutcome:
      'October 1987’s crash remains a case study in gap risk and liquidity. Use it to practice calm process — not to chase historical patterns.',
    collectionIds: ['crashes', 'risk_management', 'uncertainty'],
    symbol: 'SPX',
    symbolLabel: 'Broad equity index (proxy)',
    interval: '1d',
    difficulty: 'advanced',
    skills: ['gap_risk', 'invalidation', 'patience'],
    eraLabel: '1987',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'You do not know whether a gap is coming — that is the point.',
      'Decide how you would protect attention if volatility explodes.',
      'Name a time budget for reassessing.',
    ],
    availableNews: [news('n1', 30, 'Uneasy tape', 'Volatility chatter rises without a clear catalyst story.')],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 36,
        prompt: 'Tape feels uneasy. What process decision do you make now?',
        mentorFollowUp: 'If the next open is a gap, what changes in your research plan?',
        teachingNote: 'Gap risk is why process plans include time and attention stops.',
        newsIdsVisible: ['n1'],
      },
      {
        id: 'c2',
        freezeIndex: 44,
        prompt: 'Uncertainty remains. Stay out, wait, or deepen research?',
        mentorFollowUp: 'What evidence would justify more research time right now?',
        teachingNote: 'Calm under ambiguity is a process skill.',
      },
    ],
    pathSeed: 198710,
    pathShape: 'gap_down',
    barCount: 50,
    academyLessonIds: ['dec-invalidation', 'dec-portfolio-risk'],
    durationMinutes: 15,
    estimatedDecisionCount: 2,
    markets: ['stocks', 'macro'],
    tradingStyles: ['day', 'swing', 'any'],
    scoringEmphasis: ['risk', 'patience', 'process'],
    educationalLinks: academyLinks(['dec-invalidation']),
    premiumOnly: true,
  },
  {
    id: 'dotcom-bubble',
    title: 'Dot-com Euphoria',
    subtitle: 'Narrative markets and late-cycle attention',
    teaser: 'Tech narratives dominate. Future path is sealed until you decide.',
    historicalOutcome:
      'The late-1990s / early-2000s tech bubble and bust reward studying narrative risk and research discipline — not “calling tops.”',
    collectionIds: ['manias', 'psychology', 'false_breakouts'],
    symbol: 'NDX',
    symbolLabel: 'Tech-heavy index (proxy)',
    interval: '1d',
    difficulty: 'intermediate',
    skills: ['narrative', 'patience', 'thesis_quality'],
    eraLabel: '1999–2000',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Optimism is crowded; valuations are stretched in the story.',
      'Your task: decide whether a thesis is warranted.',
      'Avoid inventing certainty — document doubt.',
    ],
    availableNews: [
      news('n1', 28, 'Tech narrative dominates', 'Optimism and story stocks crowd attention.'),
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 34,
        prompt: 'Euphoria is loud. Research more, wait, or skip?',
        mentorFollowUp: 'What evidence would make you reduce attention to this narrative?',
        teachingNote: 'Manias punish late certainty. Waiting is often the skill.',
        newsIdsVisible: ['n1'],
      },
      {
        id: 'c2',
        freezeIndex: 50,
        prompt: 'Momentum continues. Reassess your research allocation.',
        mentorFollowUp: 'Are you updating facts — or defending a story?',
        teachingNote: 'Blind practice separates process from outcome luck.',
      },
    ],
    pathSeed: 200003,
    pathShape: 'whipsaw',
    barCount: 70,
    academyLessonIds: ['dec-setup-quality', 'dec-time-budget'],
    durationMinutes: 20,
    estimatedDecisionCount: 2,
    markets: ['stocks'],
    tradingStyles: ['swing', 'position', 'any'],
    scoringEmphasis: ['evidence', 'alternatives', 'patience'],
    educationalLinks: academyLinks(['dec-setup-quality']),
  },
  {
    id: 'svb-stress',
    title: '2023 — Banking Crisis',
    subtitle: 'Confidence, deposits, and speed',
    teaser: 'Banking headlines accelerate. You cannot see the resolution yet.',
    historicalOutcome:
      'Silicon Valley Bank’s 2023 stress episode showed how fast confidence can break. Educational focus: regime recognition and attention triage.',
    collectionIds: ['featured', 'crashes', 'regime_changes', 'risk_management'],
    symbol: 'XLF',
    symbolLabel: 'Financials sector (proxy)',
    interval: '1d',
    difficulty: 'intermediate',
    skills: ['regime', 'speed', 'risk'],
    eraLabel: '2023',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Confidence can reprice faster than fundamentals updates.',
      'Decide what research question is worth your next hour.',
      'Write an invalidation that is time-based, not hope-based.',
    ],
    availableNews: [
      news('n1', 22, 'Deposit-stress chatter', 'Regional bank confidence stories accelerate.'),
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 30,
        prompt: 'Deposit-stress chatter rises. What do you do?',
        mentorFollowUp: 'Is this a watchlist item or a deep-research project — and why?',
        teachingNote: 'Fast confidence shocks reward pre-committed attention budgets.',
        newsIdsVisible: ['n1'],
      },
      {
        id: 'c2',
        freezeIndex: 40,
        prompt: 'Speed increases. Protect attention or form a hypothesis?',
        mentorFollowUp: 'What information are you missing before researching further?',
        teachingNote: 'Speed regimes punish vague research questions.',
      },
    ],
    pathSeed: 202303,
    pathShape: 'gap_down',
    barCount: 48,
    academyLessonIds: ['dec-regime', 'dec-portfolio-risk'],
    durationMinutes: 15,
    estimatedDecisionCount: 2,
    markets: ['stocks', 'macro'],
    tradingStyles: ['swing', 'day', 'any'],
    scoringEmphasis: ['risk', 'information_use', 'process'],
    educationalLinks: academyLinks(['dec-regime']),
  },
  {
    id: 'ftx-collapse',
    title: '2022 — Crypto Collapse',
    subtitle: 'Counterparty risk as a decision filter',
    teaser: 'Crypto venue trust is questioned. Outcome path remains hidden.',
    historicalOutcome:
      'The FTX collapse highlighted counterparty and custody risk. Replay trains skepticism and process — not crypto trade ideas.',
    collectionIds: ['crypto', 'risk_management', 'uncertainty'],
    symbol: 'BTC',
    symbolLabel: 'Crypto proxy (educational)',
    interval: '1d',
    difficulty: 'advanced',
    skills: ['counterparty', 'risk', 'skip'],
    eraLabel: '2022',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Trust and custody risk can dominate price narratives.',
      'Skipping research is allowed when the question is poorly framed.',
      'Document what you refuse to research until clarity improves.',
    ],
    availableNews: [
      news('n1', 20, 'Venue trust questioned', 'Counterparty and custody narratives intensify.'),
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 28,
        prompt: 'Trust headlines worsen. Research, wait, or protect attention?',
        mentorFollowUp: 'What would need to be true before this deserves a thesis?',
        teachingNote: 'Skipping is a first-class decision when risk is opaque.',
        newsIdsVisible: ['n1'],
      },
      {
        id: 'c2',
        freezeIndex: 40,
        prompt: 'Opacity remains. Reassess your research filter.',
        mentorFollowUp: 'Are you reacting to price — or following a custody risk process?',
        teachingNote: 'Process under opacity beats narrative chase.',
      },
    ],
    pathSeed: 202211,
    pathShape: 'crash',
    barCount: 52,
    academyLessonIds: ['dec-portfolio-risk', 'dec-time-budget'],
    durationMinutes: 20,
    estimatedDecisionCount: 2,
    markets: ['crypto'],
    tradingStyles: ['swing', 'day', 'any'],
    scoringEmphasis: ['risk', 'alternatives', 'process'],
    educationalLinks: academyLinks(['dec-portfolio-risk']),
    premiumOnly: true,
  },
  {
    id: 'inflation-shock-2022',
    title: '2022 — Inflation Shock',
    subtitle: 'Policy, rates, and research triage',
    teaser: 'Inflation prints keep surprising. The forward path stays sealed.',
    historicalOutcome:
      '2022’s inflation and rate-shock year forced regime updates across assets. Educational focus: updating theses without chasing every print.',
    collectionIds: ['featured', 'policy', 'regime_changes', 'uncertainty'],
    symbol: 'SPX',
    symbolLabel: 'Broad equity index (proxy)',
    interval: '1d',
    difficulty: 'intermediate',
    skills: ['regime', 'macro', 'patience'],
    eraLabel: '2022',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Macro prints are arriving faster than narratives can settle.',
      'Your job is research allocation across shifting regimes.',
      'Name what would change your working macro thesis.',
    ],
    availableNews: [
      news('n1', 18, 'Hot inflation print', 'Price-pressure headlines dominate the session.'),
      news('n2', 34, 'Policy path uncertainty', 'Rate expectations become the research battleground.'),
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 26,
        prompt: 'Another hot print. How do you allocate the next research block?',
        mentorFollowUp: 'What evidence supports your current macro view — and what would change it?',
        teachingNote: 'Macro rooms reward named invalidation of the regime thesis.',
        newsIdsVisible: ['n1'],
      },
      {
        id: 'c2',
        freezeIndex: 42,
        prompt: 'Policy uncertainty rises. Research further, wait, or protect attention?',
        mentorFollowUp: 'Would you research this further or skip until the next data cluster?',
        teachingNote: 'Patience under macro noise is a process edge.',
        newsIdsVisible: ['n1', 'n2'],
      },
    ],
    pathSeed: 202206,
    pathShape: 'whipsaw',
    barCount: 58,
    academyLessonIds: ['dec-regime', 'dec-time-budget'],
    durationMinutes: 20,
    estimatedDecisionCount: 2,
    markets: ['stocks', 'macro', 'forex'],
    tradingStyles: ['swing', 'position', 'any'],
    scoringEmphasis: ['information_use', 'invalidation', 'patience'],
    educationalLinks: academyLinks(['dec-regime']),
  },
  {
    id: 'brexit-night',
    title: 'Brexit Night Surprise',
    subtitle: 'Binary events and research plans',
    teaser: 'A binary political outcome approaches. Post-event path is sealed.',
    historicalOutcome:
      'The 2016 Brexit referendum surprised markets. Use this room to practice pre-committing research plans around binary events.',
    collectionIds: ['policy', 'uncertainty', 'psychology'],
    symbol: 'GBPUSD',
    symbolLabel: 'FX proxy (educational reconstruction)',
    interval: '1h',
    difficulty: 'intermediate',
    skills: ['binary_event', 'plan', 'patience'],
    eraLabel: '2016',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Binary events reward plans made before the print.',
      'You will not see the result until you decide.',
      'Focus on process: what will you research if either side wins?',
    ],
    availableNews: [
      news('n1', 30, 'Binary outcome approaches', 'Polling narratives conflict; event risk is high.'),
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 40,
        prompt: 'Hours before the binary. What is your research plan?',
        mentorFollowUp: 'Did you pre-commit an attention budget for both outcomes?',
        teachingNote: 'Binary nights are about plans, not predictions.',
        newsIdsVisible: ['n1'],
      },
      {
        id: 'c2',
        freezeIndex: 56,
        prompt: 'Still pre-result. Stay out, wait, or form a hypothesis?',
        mentorFollowUp: 'What is the downside if your assumption about the vote is wrong?',
        teachingNote: 'Pre-commitment beats improvisation after the print.',
      },
    ],
    pathSeed: 201606,
    pathShape: 'whipsaw',
    barCount: 72,
    academyLessonIds: ['dec-time-budget', 'dec-invalidation'],
    durationMinutes: 20,
    estimatedDecisionCount: 2,
    markets: ['forex', 'macro'],
    tradingStyles: ['day', 'swing', 'any'],
    scoringEmphasis: ['alternatives', 'patience', 'process'],
    educationalLinks: academyLinks(['dec-time-budget']),
  },
  {
    id: 'nvidia-earnings',
    title: 'Mega-Cap Earnings Night',
    subtitle: 'Narrative pivots without hindsight',
    teaser: 'A mega-cap report is imminent. Post-print path stays hidden.',
    historicalOutcome:
      'NVIDIA earnings nights have repeatedly reset AI narratives. Practice thesis quality and invalidation — never treat past prints as signals.',
    collectionIds: ['featured', 'earnings', 'false_breakouts'],
    symbol: 'NVDA',
    symbolLabel: 'Mega-cap tech (proxy)',
    interval: '1h',
    difficulty: 'foundation',
    skills: ['earnings', 'thesis_quality', 'invalidation'],
    eraLabel: '2023–2024',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Earnings can invalidate a narrative in one print.',
      'Decide whether you need a written thesis before the event.',
      'Name what would make you stop researching this name.',
    ],
    availableNews: [
      news('n1', 24, 'Earnings approaching', 'Narrative expectations are elevated pre-print.'),
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 36,
        prompt: 'Pre-print: research more, write thesis, wait, or skip?',
        mentorFollowUp: 'What is the single research question you would answer after the print?',
        teachingNote: 'Earnings rooms train question quality, not prediction.',
        newsIdsVisible: ['n1'],
        hypothesisPrompt: 'Write a one-sentence pre-print thesis or choose skip.',
      },
      {
        id: 'c2',
        freezeIndex: 52,
        prompt: 'Post-print tape is live (still blind to further future). Reassess.',
        mentorFollowUp: 'Are you updating the thesis — or defending the pre-print story?',
        teachingNote: 'Process scores reward named invalidation and calm updates.',
      },
    ],
    pathSeed: 202405,
    pathShape: 'meltup',
    barCount: 64,
    academyLessonIds: ['dec-setup-quality', 'dec-invalidation'],
    durationMinutes: 15,
    estimatedDecisionCount: 2,
    markets: ['stocks'],
    tradingStyles: ['day', 'swing', 'any'],
    scoringEmphasis: ['evidence', 'invalidation', 'process'],
    educationalLinks: academyLinks(['dec-setup-quality', 'dec-invalidation']),
  },
  {
    id: 'tesla-rally',
    title: 'Narrative Rally Stretch',
    subtitle: 'Momentum, story, and research FOMO',
    teaser: 'A story stock is running. You cannot see how far — by design.',
    historicalOutcome:
      'Tesla rally stretches illustrate narrative momentum and FOMO. Educational aim: attention discipline and thesis hygiene.',
    collectionIds: ['manias', 'psychology', 'earnings'],
    symbol: 'TSLA',
    symbolLabel: 'Story equity (proxy)',
    interval: '1d',
    difficulty: 'foundation',
    skills: ['narrative', 'attention', 'patience'],
    eraLabel: '2020+',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Momentum feels obvious in hindsight — you do not have hindsight here.',
      'Ask whether this deserves research time vs. a skip.',
      'Write a reasoning note that a coach could grade.',
    ],
    availableNews: [news('n1', 20, 'Story heats up', 'Narrative momentum attracts attention.')],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 32,
        prompt: 'The narrative is heating up. What would you do?',
        mentorFollowUp: 'Is FOMO driving the decision, or a clear research question?',
        teachingNote: 'Rallies without a research question are attention traps.',
        newsIdsVisible: ['n1'],
      },
      {
        id: 'c2',
        freezeIndex: 44,
        prompt: 'Momentum continues. Stay out or form a hypothesis?',
        mentorFollowUp: 'What would change your mind about researching this further?',
        teachingNote: 'Foundation rooms train naming FOMO without clinical language.',
      },
    ],
    pathSeed: 202011,
    pathShape: 'meltup',
    barCount: 56,
    academyLessonIds: ['dec-time-budget', 'dec-setup-quality'],
    durationMinutes: 10,
    estimatedDecisionCount: 2,
    markets: ['stocks'],
    tradingStyles: ['day', 'swing', 'any'],
    scoringEmphasis: ['patience', 'alternatives', 'process'],
    educationalLinks: academyLinks(['dec-time-budget']),
  },
  {
    id: 'false-breakout-drill',
    title: 'False Breakout Drill',
    subtitle: 'Structure that invites chase',
    teaser: 'A level breaks. Whether it holds is hidden until you decide.',
    historicalOutcome:
      'False breakouts are common process traps. This short room trains waiting for confirmation and naming invalidation — never chasing the first poke.',
    collectionIds: ['false_breakouts', 'psychology', 'featured'],
    symbol: 'SPY',
    symbolLabel: 'Index ETF proxy',
    interval: '1h',
    difficulty: 'foundation',
    skills: ['invalidation', 'patience', 'structure'],
    eraLabel: 'Generic educational',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'A level has been tested; you cannot see if acceptance follows.',
      'Decide whether this is research-worthy or a skip.',
      'Name invalidation before deepening.',
    ],
    availableNews: [],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 24,
        prompt: 'Level breaks on the tape. Observe, research, or stay out?',
        mentorFollowUp: 'What evidence would confirm acceptance vs a false break?',
        teachingNote: 'First poke is often noise. Process waits for evidence.',
        availableDataNotes: ['Intraday structure through freeze only'],
        choices: ['wait', 'research_more', 'skip', 'protect_attention', 'write_thesis'],
      },
      {
        id: 'c2',
        freezeIndex: 36,
        prompt: 'Still ambiguous. Reassess your research allocation.',
        mentorFollowUp: 'Are you reacting to price or following your confirmation checklist?',
        teachingNote: 'Short sessions reward checklist discipline.',
      },
    ],
    pathSeed: 424242,
    pathShape: 'whipsaw',
    barCount: 48,
    academyLessonIds: ['dec-invalidation'],
    durationMinutes: 10,
    estimatedDecisionCount: 2,
    markets: ['stocks'],
    tradingStyles: ['day', 'scalp', 'any'],
    scoringEmphasis: ['invalidation', 'patience', 'evidence'],
    educationalLinks: academyLinks(['dec-invalidation']),
  },
];

export function getReplayTvEpisode(id: string): ReplayTvEpisode | undefined {
  return REPLAY_TV_EPISODES.find((e) => e.id === id);
}

export function listEpisodesForCollection(collectionId: string): ReplayTvEpisode[] {
  return REPLAY_TV_EPISODES.filter((e) =>
    e.collectionIds.includes(collectionId as ReplayTvEpisode['collectionIds'][number]),
  );
}

export function listShortSessions(maxMinutes = 15): ReplayTvEpisode[] {
  return REPLAY_TV_EPISODES.filter((e) => e.durationMinutes <= maxMinutes);
}

export function listSessionsAroundMinutes(minutes: number, tolerance = 5): ReplayTvEpisode[] {
  return REPLAY_TV_EPISODES.filter(
    (e) => Math.abs(e.durationMinutes - minutes) <= tolerance,
  );
}

export function listByDifficulty(
  difficulty: ReplayTvEpisode['difficulty'] | ReplayTvEpisode['difficulty'][],
): ReplayTvEpisode[] {
  const set = new Set(Array.isArray(difficulty) ? difficulty : [difficulty]);
  return REPLAY_TV_EPISODES.filter((e) => set.has(e.difficulty));
}
