import type {
  ReplayTvCollection,
  ReplayTvEpisode,
} from '@/features/decision-replay-tv/types/replay-tv.types';

export const REPLAY_TV_COLLECTIONS: ReplayTvCollection[] = [
  {
    id: 'featured',
    title: 'Featured',
    description: 'Start here — spoiler-safe historical decision rooms.',
  },
  {
    id: 'crashes',
    title: 'Crashes & Liquidity',
    description: 'Stress regimes where attention and invalidation matter most.',
  },
  {
    id: 'manias',
    title: 'Manias & Crowds',
    description: 'Crowded narratives, squeezes, and attention traps.',
  },
  {
    id: 'policy',
    title: 'Policy Shocks',
    description: 'Macro and political surprises that reprice risk.',
  },
  {
    id: 'earnings',
    title: 'Earnings Moments',
    description: 'Single-name narrative pivots without hindsight.',
  },
  {
    id: 'crypto',
    title: 'Crypto Stress',
    description: 'Trust and liquidity shocks in digital markets.',
  },
];

const educationalNote =
  'Educational reconstruction for decision practice. Bars are sample/approximate — not exchange ticks. Outcomes are spoiler-gated until reveal.';

export const REPLAY_TV_EPISODES: ReplayTvEpisode[] = [
  {
    id: 'covid-crash',
    title: 'COVID Liquidity Shock',
    subtitle: 'When risk assets reprice overnight',
    teaser: 'A calm trend meets an accelerating fear regime. Future path hidden.',
    historicalOutcome:
      'Historically, early 2020 saw a violent liquidity-driven drawdown followed by an extraordinary policy response and recovery. The lesson is process under stress — not a forecast template.',
    collectionIds: ['featured', 'crashes'],
    symbol: 'SPX',
    symbolLabel: 'Broad equity index (proxy)',
    interval: '1d',
    difficulty: 'intermediate',
    skills: ['regime', 'invalidation', 'time_budget'],
    eraLabel: '2020',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Macro headlines are escalating; volatility is waking up.',
      'Your job is research allocation — not predicting the bottom.',
      'Name what would make you stop watching this tape.',
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 28,
        prompt: 'Volatility is rising. What would you do with your research attention?',
        mentorFollowUp: 'What invalidation would force you to step away — a level, a time budget, or a regime change?',
        teachingNote: 'Stress regimes punish overconfidence. Protecting attention is a valid decision.',
      },
      {
        id: 'c2',
        freezeIndex: 42,
        prompt: 'The move has accelerated. Reassess: research more, wait, or protect attention?',
        mentorFollowUp: 'Are you updating your thesis — or chasing the narrative because others are?',
        teachingNote: 'Blind replay trains process under uncertainty. Outcome knowledge comes later.',
      },
    ],
    pathSeed: 202003,
    pathShape: 'crash',
    barCount: 60,
    academyLessonIds: ['dec-regime', 'dec-invalidation'],
  },
  {
    id: 'gamestop-squeeze',
    title: 'Meme Squeeze Pressure',
    subtitle: 'Crowds, short interest, and attention',
    teaser: 'A beaten-down name starts attracting unusual attention. Path hidden.',
    historicalOutcome:
      'The GameStop episode became a textbook attention/squeeze narrative. Educational focus: process under crowd pressure — never a playbook to copy.',
    collectionIds: ['featured', 'manias'],
    symbol: 'GME',
    symbolLabel: 'Single-name equity (proxy)',
    interval: '1d',
    difficulty: 'advanced',
    skills: ['attention', 'crowd', 'thesis_quality'],
    eraLabel: '2021',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Social chatter and short interest dominate the story.',
      'Liquidity can disappear when everyone wants the same door.',
      'Decide how much research time this deserves — not a price target.',
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 30,
        prompt: 'Attention is spiking. Is this worth a thesis — or a skip?',
        mentorFollowUp: 'What would make this a research trap rather than a research priority?',
        teachingNote: 'Crowd episodes often reward waiting for a clear research question.',
      },
      {
        id: 'c2',
        freezeIndex: 48,
        prompt: 'Price action is violent. Protect attention or write a structured thesis?',
        mentorFollowUp: 'Can you name an invalidation that is not “it stopped going up”?',
        teachingNote: 'Process quality beats narrative excitement.',
      },
    ],
    pathSeed: 202101,
    pathShape: 'squeeze',
    barCount: 64,
    academyLessonIds: ['dec-time-budget', 'dec-setup-quality'],
  },
  {
    id: 'lehman-weekend',
    title: 'Lehman Weekend Fear',
    subtitle: 'Systemic risk and research triage',
    teaser: 'Credit stress headlines intensify. You cannot see what comes next.',
    historicalOutcome:
      'The Lehman Brothers collapse marked a systemic phase of the Global Financial Crisis. Replay trains triage and invalidation — not crisis trading.',
    collectionIds: ['crashes'],
    symbol: 'SPX',
    symbolLabel: 'Broad equity index (proxy)',
    interval: '1d',
    difficulty: 'advanced',
    skills: ['regime', 'risk', 'patience'],
    eraLabel: '2008',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Financial plumbing stress is the story — not a single ticker.',
      'Your edge here is deciding what to study, not predicting the weekend.',
      'Write what would prove your working view wrong.',
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 32,
        prompt: 'Credit headlines worsen. How do you allocate research time?',
        mentorFollowUp: 'Is your plan process-driven, or are you reacting to fear?',
        teachingNote: 'Systemic regimes demand smaller research bets and clearer stops.',
      },
    ],
    pathSeed: 200809,
    pathShape: 'slow_bleed',
    barCount: 55,
    academyLessonIds: ['dec-regime', 'dec-portfolio-risk'],
  },
  {
    id: 'black-monday',
    title: 'Black Monday Shock',
    subtitle: 'Gap risk and decision quality',
    teaser: 'A calm stretch ends. The next bars are hidden on purpose.',
    historicalOutcome:
      'October 1987’s crash remains a case study in gap risk and liquidity. Use it to practice calm process — not to chase historical patterns.',
    collectionIds: ['crashes'],
    symbol: 'SPX',
    symbolLabel: 'Broad equity index (proxy)',
    interval: '1d',
    difficulty: 'advanced',
    skills: ['gap_risk', 'invalidation', 'patience'],
    eraLabel: '1987',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'You do not know whether a gap is coming — that is the point.',
      'Decide how you would protect attention if volatility explodes.',
      'Name a time budget for reassessing.',
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 36,
        prompt: 'Tape feels uneasy. What process decision do you make now?',
        mentorFollowUp: 'If the next open is a gap, what changes in your research plan?',
        teachingNote: 'Gap risk is why process plans include time and attention stops.',
      },
    ],
    pathSeed: 198710,
    pathShape: 'gap_down',
    barCount: 50,
    academyLessonIds: ['dec-invalidation', 'dec-portfolio-risk'],
  },
  {
    id: 'dotcom-bubble',
    title: 'Dot-com Euphoria',
    subtitle: 'Narrative markets and late-cycle attention',
    teaser: 'Tech narratives dominate. Future path is sealed until you decide.',
    historicalOutcome:
      'The late-1990s / early-2000s tech bubble and bust reward studying narrative risk and research discipline — not “calling tops.”',
    collectionIds: ['manias'],
    symbol: 'NDX',
    symbolLabel: 'Tech-heavy index (proxy)',
    interval: '1d',
    difficulty: 'intermediate',
    skills: ['narrative', 'patience', 'thesis_quality'],
    eraLabel: '1999–2000',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Optimism is crowded; valuations are stretched in the story.',
      'Your task: decide whether a thesis is warranted.',
      'Avoid inventing certainty — document doubt.',
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 34,
        prompt: 'Euphoria is loud. Research more, wait, or skip?',
        mentorFollowUp: 'What evidence would make you reduce attention to this narrative?',
        teachingNote: 'Manias punish late certainty. Waiting is often the skill.',
      },
      {
        id: 'c2',
        freezeIndex: 50,
        prompt: 'Momentum continues. Reassess your research allocation.',
        mentorFollowUp: 'Are you updating facts — or defending a story?',
        teachingNote: 'Blind practice separates process from outcome luck.',
      },
    ],
    pathSeed: 200003,
    pathShape: 'whipsaw',
    barCount: 70,
    academyLessonIds: ['dec-setup-quality', 'dec-time-budget'],
  },
  {
    id: 'svb-stress',
    title: 'Regional Bank Stress',
    subtitle: 'Confidence, deposits, and speed',
    teaser: 'Banking headlines accelerate. You cannot see the resolution yet.',
    historicalOutcome:
      'Silicon Valley Bank’s 2023 stress episode showed how fast confidence can break. Educational focus: regime recognition and attention triage.',
    collectionIds: ['featured', 'crashes'],
    symbol: 'XLF',
    symbolLabel: 'Financials sector (proxy)',
    interval: '1d',
    difficulty: 'intermediate',
    skills: ['regime', 'speed', 'risk'],
    eraLabel: '2023',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Confidence can reprice faster than fundamentals updates.',
      'Decide what research question is worth your next hour.',
      'Write an invalidation that is time-based, not hope-based.',
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 30,
        prompt: 'Deposit-stress chatter rises. What do you do?',
        mentorFollowUp: 'Is this a watchlist item or a deep-research project — and why?',
        teachingNote: 'Fast confidence shocks reward pre-committed attention budgets.',
      },
    ],
    pathSeed: 202303,
    pathShape: 'gap_down',
    barCount: 48,
    academyLessonIds: ['dec-regime', 'dec-portfolio-risk'],
  },
  {
    id: 'ftx-collapse',
    title: 'Exchange Trust Break',
    subtitle: 'Counterparty risk as a decision filter',
    teaser: 'Crypto venue trust is questioned. Outcome path remains hidden.',
    historicalOutcome:
      'The FTX collapse highlighted counterparty and custody risk. Replay trains skepticism and process — not crypto trade ideas.',
    collectionIds: ['crypto'],
    symbol: 'BTC',
    symbolLabel: 'Crypto proxy (educational)',
    interval: '1d',
    difficulty: 'advanced',
    skills: ['counterparty', 'risk', 'skip'],
    eraLabel: '2022',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Trust and custody risk can dominate price narratives.',
      'Skipping research is allowed when the question is poorly framed.',
      'Document what you refuse to research until clarity improves.',
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 28,
        prompt: 'Trust headlines worsen. Research, wait, or protect attention?',
        mentorFollowUp: 'What would need to be true before this deserves a thesis?',
        teachingNote: 'Skipping is a first-class decision when risk is opaque.',
      },
    ],
    pathSeed: 202211,
    pathShape: 'crash',
    barCount: 52,
    academyLessonIds: ['dec-portfolio-risk', 'dec-time-budget'],
  },
  {
    id: 'brexit-night',
    title: 'Brexit Night Surprise',
    subtitle: 'Binary events and research plans',
    teaser: 'A binary political outcome approaches. Post-event path is sealed.',
    historicalOutcome:
      'The 2016 Brexit referendum surprised markets. Use this room to practice pre-committing research plans around binary events.',
    collectionIds: ['policy'],
    symbol: 'GBPUSD',
    symbolLabel: 'FX proxy (educational reconstruction)',
    interval: '1h',
    difficulty: 'intermediate',
    skills: ['binary_event', 'plan', 'patience'],
    eraLabel: '2016',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Binary events reward plans made before the print.',
      'You will not see the result until you decide.',
      'Focus on process: what will you research if either side wins?',
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 40,
        prompt: 'Hours before the binary. What is your research plan?',
        mentorFollowUp: 'Did you pre-commit an attention budget for both outcomes?',
        teachingNote: 'Binary nights are about plans, not predictions.',
      },
    ],
    pathSeed: 201606,
    pathShape: 'whipsaw',
    barCount: 72,
    academyLessonIds: ['dec-time-budget', 'dec-invalidation'],
  },
  {
    id: 'nvidia-earnings',
    title: 'Mega-Cap Earnings Night',
    subtitle: 'Narrative pivots without hindsight',
    teaser: 'A mega-cap report is imminent. Post-print path stays hidden.',
    historicalOutcome:
      'NVIDIA earnings nights have repeatedly reset AI narratives. Practice thesis quality and invalidation — never treat past prints as signals.',
    collectionIds: ['featured', 'earnings'],
    symbol: 'NVDA',
    symbolLabel: 'Mega-cap tech (proxy)',
    interval: '1h',
    difficulty: 'foundation',
    skills: ['earnings', 'thesis_quality', 'invalidation'],
    eraLabel: '2023–2024',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Earnings can invalidate a narrative in one print.',
      'Decide whether you need a written thesis before the event.',
      'Name what would make you stop researching this name.',
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 36,
        prompt: 'Pre-print: research more, write thesis, wait, or skip?',
        mentorFollowUp: 'What is the single research question you would answer after the print?',
        teachingNote: 'Earnings rooms train question quality, not prediction.',
      },
      {
        id: 'c2',
        freezeIndex: 52,
        prompt: 'Post-print tape is live (still blind to further future). Reassess.',
        mentorFollowUp: 'Are you updating the thesis — or defending the pre-print story?',
        teachingNote: 'Process scores reward named invalidation and calm updates.',
      },
    ],
    pathSeed: 202405,
    pathShape: 'meltup',
    barCount: 64,
    academyLessonIds: ['dec-setup-quality', 'dec-invalidation'],
  },
  {
    id: 'tesla-rally',
    title: 'Narrative Rally Stretch',
    subtitle: 'Momentum, story, and research FOMO',
    teaser: 'A story stock is running. You cannot see how far — by design.',
    historicalOutcome:
      'Tesla rally stretches illustrate narrative momentum and FOMO. Educational aim: attention discipline and thesis hygiene.',
    collectionIds: ['manias', 'earnings'],
    symbol: 'TSLA',
    symbolLabel: 'Story equity (proxy)',
    interval: '1d',
    difficulty: 'foundation',
    skills: ['narrative', 'attention', 'patience'],
    eraLabel: '2020+',
    dataKind: 'sample',
    provenanceNote: educationalNote,
    contextBullets: [
      'Momentum feels obvious in hindsight — you do not have hindsight here.',
      'Ask whether this deserves research time vs. a skip.',
      'Write a reasoning note that a coach could grade.',
    ],
    checkpoints: [
      {
        id: 'c1',
        freezeIndex: 32,
        prompt: 'The narrative is heating up. What would you do?',
        mentorFollowUp: 'Is FOMO driving the decision, or a clear research question?',
        teachingNote: 'Rallies without a research question are attention traps.',
      },
    ],
    pathSeed: 202011,
    pathShape: 'meltup',
    barCount: 56,
    academyLessonIds: ['dec-time-budget', 'dec-setup-quality'],
  },
];

export function getReplayTvEpisode(id: string): ReplayTvEpisode | undefined {
  return REPLAY_TV_EPISODES.find((e) => e.id === id);
}

export function listEpisodesForCollection(collectionId: string): ReplayTvEpisode[] {
  return REPLAY_TV_EPISODES.filter((e) => e.collectionIds.includes(collectionId as never));
}
