name: Create preview builds

jobs:
  build_android:
    name: Build Android preview
    type: build
    params:
      platform: android
      profile: preview
  build_ios:
    name: Build iOS preview
    type: build
    params:
      platform: ios
      profile: preview
